#!/bin/sh
# Generates build/guest-cross.ini: the meson cross file for miniBox's
# musl/libstdc++ guest toolchain. Used by waterbox/build-deps.sh (M0: zlib,
# glib, pixman) and by the xemu guest configure (M1).
#
# Prereq: a miniBox checkout built WITH the C++ guest toolchain:
#   meson setup <miniBox>/build/meson-cpp -Dguest_cpp=true && ninja -C <miniBox>/build/meson-cpp
#
# Usage: ./waterbox/setup-guest.sh [-m <miniBox dir>]
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
mb="${MINIBOX_DIR:-$HOME/chimera/extern/tools/chimera-common-minibox}"
while getopts "m:" opt; do
	case "$opt" in
		m) mb="$OPTARG" ;;
		*) exit 2 ;;
	esac
done
mb="$(cd "$mb" && pwd)"
mbuild="$mb/build/meson-cpp"
sr="$mbuild/guest-sysroot"
gccver="$(gcc -dumpfullversion)"

[ -f "$sr/lib/libstdc++.a" ] || {
	echo "miniBox C++ guest toolchain missing at $sr." >&2
	echo "Run: meson setup $mbuild $mb -Dguest_cpp=true && ninja -C $mbuild" >&2
	exit 1
}

mkdir -p "$root/build"
cross="$root/build/guest-cross.ini"
deps="$root/build/guest-deps"

# The waterbox code-model flags + the musl specs, on every compile and link.
# pkg_config_libdir points ONLY at the guest deps prefix, so no host library
# can ever satisfy a dependency of the guest build.
cat > "$cross" <<EOF
# generated by waterbox/setup-guest.sh - machine-local paths, do not commit
[binaries]
c = 'gcc'
cpp = 'g++'
ar = 'ar'
strip = 'strip'
pkg-config = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
needs_exe_wrapper = true
minibox_dir = '$mb'
minibox_build = '$mbuild'
guest_sysroot = '$sr'
pkg_config_libdir = ['$deps/lib/pkgconfig', '$deps/share/pkgconfig', '$deps/lib/x86_64-linux-gnu/pkgconfig']

[built-in options]
c_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-stack-protector', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-DCHIMERA_GUEST', '-DPIXMAN_NO_TLS', '-I$mb/extern/emulibc', '-I$mb/source/guest/include']
cpp_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-stack-protector', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-fexceptions', '-DCHIMERA_GUEST', '-I$mb/extern/emulibc', '-I$mb/source/guest/include', '-I$sr/include/c++/$gccver', '-I$sr/include/c++/$gccver/x86_64-linux-musl']
c_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
cpp_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
EOF

echo "cross file written: $cross"

# ---- guest QEMU toolchain wrappers ----------------------------------------
# xemu's configure needs a --cross-prefix toolchain: wrappers that inject the
# musl specs exactly once (the specs file is not idempotent), give g++ the
# guest libstdc++ headers, append the waterbox link recipe only when actually
# linking, and confine pkg-config to the guest deps.
deps="$root/build/guest-deps"
bin="$root/build/guest-bin"
mkdir -p "$bin"
mbo="$mbuild/source/guest"

gcc -specs "$sr/lib/musl-gcc.specs" -mcmodel=large -mstack-protector-guard=global -fno-stack-protector -fno-pic -fno-pie -fcf-protection=none -O2 -c "$here/guest-ucontext.c" -o "$root/build/guest-ucontext.o"

{
	echo '#!/bin/sh'
	echo 'case " $* " in'
	echo '*" -c "*|*" -E "*|*" -S "*|*"--version"*|*"-dumpmachine"*)'
	echo "	exec gcc -specs \"$sr/lib/musl-gcc.specs\" \"\$@\" ;;"
	echo 'esac'
	echo "exec gcc -specs \"$sr/lib/musl-gcc.specs\" \"\$@\" -T \"$mb/source/guest/linkscript.T\" -Wl,--no-relax -Wl,-z,stack-size=8388608 -Wl,-u,pthread_once -Wl,-u,pthread_cond_wait -Wl,-u,pthread_cond_broadcast -Wl,-u,pthread_key_create \"$mbo/cxxglue.c.o\" \"$mbo/emulibc.c.o\" \"$root/build/guest-ucontext.o\" -L\"$sr/lib\" -lstdc++ -lgcc -lgcc_eh -lc"
} > "$root/build/guest-cc"
sed "s|exec gcc -specs \"$sr/lib/musl-gcc.specs\" \"\$@\"|exec g++ -specs \"$sr/lib/musl-gcc.specs\" -I\"$sr/include/c++/$gccver\" -I\"$sr/include/c++/$gccver/x86_64-linux-musl\" \"\$@\"|g" "$root/build/guest-cc" > "$root/build/guest-cxx"
chmod +x "$root/build/guest-cc" "$root/build/guest-cxx"

for t in ar strip ranlib nm objcopy ld; do
	ln -sf "$(command -v $t)" "$bin/x86_64-chimera-linux-musl-$t"
done
ln -sf "$root/build/guest-cc" "$bin/x86_64-chimera-linux-musl-gcc"
ln -sf "$root/build/guest-cxx" "$bin/x86_64-chimera-linux-musl-g++"
{
	echo '#!/bin/sh'
	echo "PKG_CONFIG_LIBDIR=\"$deps/lib/pkgconfig:$deps/lib/x86_64-linux-gnu/pkgconfig:$deps/share/pkgconfig\" exec pkg-config \"\$@\""
} > "$bin/x86_64-chimera-linux-musl-pkg-config"
chmod +x "$bin/x86_64-chimera-linux-musl-pkg-config"
echo "guest toolchain wrappers written: $bin"

# ---- configure the guest QEMU ---------------------------------------------
sh "$here/apply-patches.sh"
mkdir -p "$root/build/qemu-guest"
cd "$root/build/qemu-guest"
"$root/extern/xemu/configure" \
	--cross-prefix="$bin/x86_64-chimera-linux-musl-" \
	--target-list=i386-softmmu \
	--extra-cflags="-mcmodel=large -mstack-protector-guard=global -fno-stack-protector -fno-pic -fno-pie -fcf-protection=none -DXBOX=1 -DCHIMERA_GUEST "-D__thread=" -I$deps/include -I$mb/extern/emulibc -I$mb/source/guest/include -I$mb/extern/jsmn -Wno-error" \
	--extra-ldflags="-static -no-pie" \
	--enable-pixman --static --disable-werror \
	--disable-sdl --disable-opengl --disable-gtk --disable-vnc \
	--disable-slirp --disable-docs --disable-tools --disable-guest-agent \
	--audio-drv-list= --disable-kvm --disable-xen --with-coroutine=ucontext
echo "guest build configured: ninja -C build/qemu-guest qemu-system-i386"
