#!/bin/sh
# Generates build/guest-cross.ini: the meson cross file for miniBox's
# musl/libstdc++ guest toolchain. Used by waterbox/build-deps.sh (M0: zlib,
# glib, pixman) and by the xemu guest configure (M1).
#
# Prereq: a miniBox checkout built WITH the C++ guest toolchain:
#   meson setup <miniBox>/build/meson-cpp -Dguest_cpp=true && ninja -C <miniBox>/build/meson-cpp
#
# Usage: ./waterbox/setup-guest.sh [-m <miniBox dir>]
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
mb="${MINIBOX_DIR:-$HOME/chimera/extern/tools/chimera-common-minibox}"
while getopts "m:" opt; do
	case "$opt" in
		m) mb="$OPTARG" ;;
		*) exit 2 ;;
	esac
done
mb="$(cd "$mb" && pwd)"
mbuild="$mb/build/meson-cpp"
sr="$mbuild/guest-sysroot"
gccver="$(gcc -dumpfullversion)"

[ -f "$sr/lib/libstdc++.a" ] || {
	echo "miniBox C++ guest toolchain missing at $sr." >&2
	echo "Run: meson setup $mbuild $mb -Dguest_cpp=true && ninja -C $mbuild" >&2
	exit 1
}

mkdir -p "$root/build"
cross="$root/build/guest-cross.ini"
deps="$root/build/guest-deps"

# The waterbox code-model flags + the musl specs, on every compile and link.
# pkg_config_libdir points ONLY at the guest deps prefix, so no host library
# can ever satisfy a dependency of the guest build.
cat > "$cross" <<EOF
# generated by waterbox/setup-guest.sh - machine-local paths, do not commit
[binaries]
c = 'gcc'
cpp = 'g++'
ar = 'ar'
strip = 'strip'
pkg-config = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
needs_exe_wrapper = true
minibox_dir = '$mb'
minibox_build = '$mbuild'
guest_sysroot = '$sr'
pkg_config_libdir = ['$deps/lib/pkgconfig', '$deps/share/pkgconfig', '$deps/lib/x86_64-linux-gnu/pkgconfig']

[built-in options]
c_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-stack-protector', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-DCHIMERA_GUEST', '-I$mb/extern/emulibc', '-I$mb/source/guest/include']
cpp_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-stack-protector', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-fexceptions', '-DCHIMERA_GUEST', '-I$mb/extern/emulibc', '-I$mb/source/guest/include', '-I$sr/include/c++/$gccver', '-I$sr/include/c++/$gccver/x86_64-linux-musl']
c_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
cpp_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
EOF

echo "cross file written: $cross"
