/* GENERATED by tools/gen-gl-bridge.py from glad's declarations.
 * Do not edit; edit the generator or the name list beside it. */

/* The guest's side: 190 entry points, each one a struct and a call
 * to the sandbox's single callback. Installing them is the whole of what makes
 * this core's renderer talk to a GPU it cannot see. */
#include <glad/gl.h>
#include <cstdint>
#include <cstdio>
#include <cstring>

#include "gl-bridge.h"
#include "gl-bridge-ops.h"

static chimera_gl_bridge_fn g_bridge;

static void GLAD_API_PTR w_glActiveTexture(GLenum texture)
{
	struct ChimeraGlArgs_glActiveTexture chimera_a;
	chimera_a.texture = texture;
	g_bridge(CHIMERA_GL_OP_glActiveTexture, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glAttachShader(GLuint program, GLuint shader)
{
	struct ChimeraGlArgs_glAttachShader chimera_a;
	chimera_a.program = program;
	chimera_a.shader = shader;
	g_bridge(CHIMERA_GL_OP_glAttachShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBeginQuery(GLenum target, GLuint id)
{
	struct ChimeraGlArgs_glBeginQuery chimera_a;
	chimera_a.target = target;
	chimera_a.id = id;
	g_bridge(CHIMERA_GL_OP_glBeginQuery, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindAttribLocation(GLuint program, GLuint index, const GLchar * name)
{
	struct ChimeraGlArgs_glBindAttribLocation chimera_a;
	chimera_a.program = program;
	chimera_a.index = index;
	chimera_a.name = name;
	g_bridge(CHIMERA_GL_OP_glBindAttribLocation, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindBuffer(GLenum target, GLuint buffer)
{
	struct ChimeraGlArgs_glBindBuffer chimera_a;
	chimera_a.target = target;
	chimera_a.buffer = buffer;
	g_bridge(CHIMERA_GL_OP_glBindBuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
{
	struct ChimeraGlArgs_glBindBufferRange chimera_a;
	chimera_a.target = target;
	chimera_a.index = index;
	chimera_a.buffer = buffer;
	chimera_a.offset = offset;
	chimera_a.size = size;
	g_bridge(CHIMERA_GL_OP_glBindBufferRange, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindFragDataLocation(GLuint program, GLuint color, const GLchar * name)
{
	struct ChimeraGlArgs_glBindFragDataLocation chimera_a;
	chimera_a.program = program;
	chimera_a.color = color;
	chimera_a.name = name;
	g_bridge(CHIMERA_GL_OP_glBindFragDataLocation, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindFragDataLocationIndexed(GLuint program, GLuint colorNumber, GLuint index, const GLchar * name)
{
	struct ChimeraGlArgs_glBindFragDataLocationIndexed chimera_a;
	chimera_a.program = program;
	chimera_a.colorNumber = colorNumber;
	chimera_a.index = index;
	chimera_a.name = name;
	g_bridge(CHIMERA_GL_OP_glBindFragDataLocationIndexed, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindFragDataLocationIndexedEXT(GLuint program, GLuint colorNumber, GLuint index, const GLchar * name)
{
	struct ChimeraGlArgs_glBindFragDataLocationIndexedEXT chimera_a;
	chimera_a.program = program;
	chimera_a.colorNumber = colorNumber;
	chimera_a.index = index;
	chimera_a.name = name;
	g_bridge(CHIMERA_GL_OP_glBindFragDataLocationIndexedEXT, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindFramebuffer(GLenum target, GLuint framebuffer)
{
	struct ChimeraGlArgs_glBindFramebuffer chimera_a;
	chimera_a.target = target;
	chimera_a.framebuffer = framebuffer;
	g_bridge(CHIMERA_GL_OP_glBindFramebuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindImageTexture(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format)
{
	struct ChimeraGlArgs_glBindImageTexture chimera_a;
	chimera_a.unit = unit;
	chimera_a.texture = texture;
	chimera_a.level = level;
	chimera_a.layered = layered;
	chimera_a.layer = layer;
	chimera_a.access = access;
	chimera_a.format = format;
	g_bridge(CHIMERA_GL_OP_glBindImageTexture, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindRenderbuffer(GLenum target, GLuint renderbuffer)
{
	struct ChimeraGlArgs_glBindRenderbuffer chimera_a;
	chimera_a.target = target;
	chimera_a.renderbuffer = renderbuffer;
	g_bridge(CHIMERA_GL_OP_glBindRenderbuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindSampler(GLuint unit, GLuint sampler)
{
	struct ChimeraGlArgs_glBindSampler chimera_a;
	chimera_a.unit = unit;
	chimera_a.sampler = sampler;
	g_bridge(CHIMERA_GL_OP_glBindSampler, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindTexture(GLenum target, GLuint texture)
{
	struct ChimeraGlArgs_glBindTexture chimera_a;
	chimera_a.target = target;
	chimera_a.texture = texture;
	g_bridge(CHIMERA_GL_OP_glBindTexture, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindTextureUnit(GLuint unit, GLuint texture)
{
	struct ChimeraGlArgs_glBindTextureUnit chimera_a;
	chimera_a.unit = unit;
	chimera_a.texture = texture;
	g_bridge(CHIMERA_GL_OP_glBindTextureUnit, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindVertexArray(GLuint array)
{
	struct ChimeraGlArgs_glBindVertexArray chimera_a;
	chimera_a.array = array;
	g_bridge(CHIMERA_GL_OP_glBindVertexArray, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
	struct ChimeraGlArgs_glBlendColor chimera_a;
	chimera_a.red = red;
	chimera_a.green = green;
	chimera_a.blue = blue;
	chimera_a.alpha = alpha;
	g_bridge(CHIMERA_GL_OP_glBlendColor, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha)
{
	struct ChimeraGlArgs_glBlendEquationSeparate chimera_a;
	chimera_a.modeRGB = modeRGB;
	chimera_a.modeAlpha = modeAlpha;
	g_bridge(CHIMERA_GL_OP_glBlendEquationSeparate, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendFunc(GLenum sfactor, GLenum dfactor)
{
	struct ChimeraGlArgs_glBlendFunc chimera_a;
	chimera_a.sfactor = sfactor;
	chimera_a.dfactor = dfactor;
	g_bridge(CHIMERA_GL_OP_glBlendFunc, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendFuncSeparate(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha)
{
	struct ChimeraGlArgs_glBlendFuncSeparate chimera_a;
	chimera_a.sfactorRGB = sfactorRGB;
	chimera_a.dfactorRGB = dfactorRGB;
	chimera_a.sfactorAlpha = sfactorAlpha;
	chimera_a.dfactorAlpha = dfactorAlpha;
	g_bridge(CHIMERA_GL_OP_glBlendFuncSeparate, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
{
	struct ChimeraGlArgs_glBlitFramebuffer chimera_a;
	chimera_a.srcX0 = srcX0;
	chimera_a.srcY0 = srcY0;
	chimera_a.srcX1 = srcX1;
	chimera_a.srcY1 = srcY1;
	chimera_a.dstX0 = dstX0;
	chimera_a.dstY0 = dstY0;
	chimera_a.dstX1 = dstX1;
	chimera_a.dstY1 = dstY1;
	chimera_a.mask = mask;
	chimera_a.filter = filter;
	g_bridge(CHIMERA_GL_OP_glBlitFramebuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBufferData(GLenum target, GLsizeiptr size, const void * data, GLenum usage)
{
	struct ChimeraGlArgs_glBufferData chimera_a;
	chimera_a.target = target;
	chimera_a.size = size;
	chimera_a.data = data;
	chimera_a.usage = usage;
	g_bridge(CHIMERA_GL_OP_glBufferData, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBufferStorage(GLenum target, GLsizeiptr size, const void * data, GLbitfield flags)
{
	struct ChimeraGlArgs_glBufferStorage chimera_a;
	chimera_a.target = target;
	chimera_a.size = size;
	chimera_a.data = data;
	chimera_a.flags = flags;
	g_bridge(CHIMERA_GL_OP_glBufferStorage, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBufferStorageEXT(GLenum target, GLsizeiptr size, const void * data, GLbitfield flags)
{
	struct ChimeraGlArgs_glBufferStorageEXT chimera_a;
	chimera_a.target = target;
	chimera_a.size = size;
	chimera_a.data = data;
	chimera_a.flags = flags;
	g_bridge(CHIMERA_GL_OP_glBufferStorageEXT, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void * data)
{
	struct ChimeraGlArgs_glBufferSubData chimera_a;
	chimera_a.target = target;
	chimera_a.offset = offset;
	chimera_a.size = size;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glBufferSubData, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLenum GLAD_API_PTR w_glCheckFramebufferStatus(GLenum target)
{
	struct ChimeraGlArgs_glCheckFramebufferStatus chimera_a;
	chimera_a.target = target;
	return (GLenum)g_bridge(CHIMERA_GL_OP_glCheckFramebufferStatus, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClear(GLbitfield mask)
{
	struct ChimeraGlArgs_glClear chimera_a;
	chimera_a.mask = mask;
	g_bridge(CHIMERA_GL_OP_glClear, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat * value)
{
	struct ChimeraGlArgs_glClearBufferfv chimera_a;
	chimera_a.buffer = buffer;
	chimera_a.drawbuffer = drawbuffer;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glClearBufferfv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint * value)
{
	struct ChimeraGlArgs_glClearBufferiv chimera_a;
	chimera_a.buffer = buffer;
	chimera_a.drawbuffer = drawbuffer;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glClearBufferiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint * value)
{
	struct ChimeraGlArgs_glClearBufferuiv chimera_a;
	chimera_a.buffer = buffer;
	chimera_a.drawbuffer = drawbuffer;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glClearBufferuiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
	struct ChimeraGlArgs_glClearColor chimera_a;
	chimera_a.red = red;
	chimera_a.green = green;
	chimera_a.blue = blue;
	chimera_a.alpha = alpha;
	g_bridge(CHIMERA_GL_OP_glClearColor, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearDepthf(GLfloat d)
{
	struct ChimeraGlArgs_glClearDepthf chimera_a;
	chimera_a.d = d;
	g_bridge(CHIMERA_GL_OP_glClearDepthf, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearStencil(GLint s)
{
	struct ChimeraGlArgs_glClearStencil chimera_a;
	chimera_a.s = s;
	g_bridge(CHIMERA_GL_OP_glClearStencil, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLenum GLAD_API_PTR w_glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout)
{
	struct ChimeraGlArgs_glClientWaitSync chimera_a;
	chimera_a.sync = sync;
	chimera_a.flags = flags;
	chimera_a.timeout = timeout;
	return (GLenum)g_bridge(CHIMERA_GL_OP_glClientWaitSync, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClipControl(GLenum origin, GLenum depth)
{
	struct ChimeraGlArgs_glClipControl chimera_a;
	chimera_a.origin = origin;
	chimera_a.depth = depth;
	g_bridge(CHIMERA_GL_OP_glClipControl, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
	struct ChimeraGlArgs_glColorMask chimera_a;
	chimera_a.red = red;
	chimera_a.green = green;
	chimera_a.blue = blue;
	chimera_a.alpha = alpha;
	g_bridge(CHIMERA_GL_OP_glColorMask, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glColorMaski(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a)
{
	struct ChimeraGlArgs_glColorMaski chimera_a;
	chimera_a.index = index;
	chimera_a.r = r;
	chimera_a.g = g;
	chimera_a.b = b;
	chimera_a.a = a;
	g_bridge(CHIMERA_GL_OP_glColorMaski, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCompileShader(GLuint shader)
{
	struct ChimeraGlArgs_glCompileShader chimera_a;
	chimera_a.shader = shader;
	g_bridge(CHIMERA_GL_OP_glCompileShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void * data)
{
	struct ChimeraGlArgs_glCompressedTexSubImage2D chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.xoffset = xoffset;
	chimera_a.yoffset = yoffset;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.format = format;
	chimera_a.imageSize = imageSize;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glCompressedTexSubImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCompressedTextureSubImage2D(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void * data)
{
	struct ChimeraGlArgs_glCompressedTextureSubImage2D chimera_a;
	chimera_a.texture = texture;
	chimera_a.level = level;
	chimera_a.xoffset = xoffset;
	chimera_a.yoffset = yoffset;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.format = format;
	chimera_a.imageSize = imageSize;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glCompressedTextureSubImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCopyImageSubData(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
{
	struct ChimeraGlArgs_glCopyImageSubData chimera_a;
	chimera_a.srcName = srcName;
	chimera_a.srcTarget = srcTarget;
	chimera_a.srcLevel = srcLevel;
	chimera_a.srcX = srcX;
	chimera_a.srcY = srcY;
	chimera_a.srcZ = srcZ;
	chimera_a.dstName = dstName;
	chimera_a.dstTarget = dstTarget;
	chimera_a.dstLevel = dstLevel;
	chimera_a.dstX = dstX;
	chimera_a.dstY = dstY;
	chimera_a.dstZ = dstZ;
	chimera_a.srcWidth = srcWidth;
	chimera_a.srcHeight = srcHeight;
	chimera_a.srcDepth = srcDepth;
	g_bridge(CHIMERA_GL_OP_glCopyImageSubData, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCopyImageSubDataEXT(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
{
	struct ChimeraGlArgs_glCopyImageSubDataEXT chimera_a;
	chimera_a.srcName = srcName;
	chimera_a.srcTarget = srcTarget;
	chimera_a.srcLevel = srcLevel;
	chimera_a.srcX = srcX;
	chimera_a.srcY = srcY;
	chimera_a.srcZ = srcZ;
	chimera_a.dstName = dstName;
	chimera_a.dstTarget = dstTarget;
	chimera_a.dstLevel = dstLevel;
	chimera_a.dstX = dstX;
	chimera_a.dstY = dstY;
	chimera_a.dstZ = dstZ;
	chimera_a.srcWidth = srcWidth;
	chimera_a.srcHeight = srcHeight;
	chimera_a.srcDepth = srcDepth;
	g_bridge(CHIMERA_GL_OP_glCopyImageSubDataEXT, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCopyImageSubDataNV(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth)
{
	struct ChimeraGlArgs_glCopyImageSubDataNV chimera_a;
	chimera_a.srcName = srcName;
	chimera_a.srcTarget = srcTarget;
	chimera_a.srcLevel = srcLevel;
	chimera_a.srcX = srcX;
	chimera_a.srcY = srcY;
	chimera_a.srcZ = srcZ;
	chimera_a.dstName = dstName;
	chimera_a.dstTarget = dstTarget;
	chimera_a.dstLevel = dstLevel;
	chimera_a.dstX = dstX;
	chimera_a.dstY = dstY;
	chimera_a.dstZ = dstZ;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.depth = depth;
	g_bridge(CHIMERA_GL_OP_glCopyImageSubDataNV, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glCopyTexSubImage2D chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.xoffset = xoffset;
	chimera_a.yoffset = yoffset;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glCopyTexSubImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCopyTextureSubImage2D(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glCopyTextureSubImage2D chimera_a;
	chimera_a.texture = texture;
	chimera_a.level = level;
	chimera_a.xoffset = xoffset;
	chimera_a.yoffset = yoffset;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glCopyTextureSubImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLuint GLAD_API_PTR w_glCreateProgram(void)
{
	return (GLuint)g_bridge(CHIMERA_GL_OP_glCreateProgram, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCreateSamplers(GLsizei n, GLuint * samplers)
{
	struct ChimeraGlArgs_glCreateSamplers chimera_a;
	chimera_a.n = n;
	chimera_a.samplers = samplers;
	g_bridge(CHIMERA_GL_OP_glCreateSamplers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLuint GLAD_API_PTR w_glCreateShader(GLenum type)
{
	struct ChimeraGlArgs_glCreateShader chimera_a;
	chimera_a.type = type;
	return (GLuint)g_bridge(CHIMERA_GL_OP_glCreateShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCreateTextures(GLenum target, GLsizei n, GLuint * textures)
{
	struct ChimeraGlArgs_glCreateTextures chimera_a;
	chimera_a.target = target;
	chimera_a.n = n;
	chimera_a.textures = textures;
	g_bridge(CHIMERA_GL_OP_glCreateTextures, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCullFace(GLenum mode)
{
	struct ChimeraGlArgs_glCullFace chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glCullFace, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDebugMessageCallback(GLDEBUGPROC callback, const void * userParam)
{
	struct ChimeraGlArgs_glDebugMessageCallback chimera_a;
	chimera_a.callback = callback;
	chimera_a.userParam = userParam;
	g_bridge(CHIMERA_GL_OP_glDebugMessageCallback, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDebugMessageControl(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint * ids, GLboolean enabled)
{
	struct ChimeraGlArgs_glDebugMessageControl chimera_a;
	chimera_a.source = source;
	chimera_a.type = type;
	chimera_a.severity = severity;
	chimera_a.count = count;
	chimera_a.ids = ids;
	chimera_a.enabled = enabled;
	g_bridge(CHIMERA_GL_OP_glDebugMessageControl, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteBuffers(GLsizei n, const GLuint * buffers)
{
	struct ChimeraGlArgs_glDeleteBuffers chimera_a;
	chimera_a.n = n;
	chimera_a.buffers = buffers;
	g_bridge(CHIMERA_GL_OP_glDeleteBuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteFramebuffers(GLsizei n, const GLuint * framebuffers)
{
	struct ChimeraGlArgs_glDeleteFramebuffers chimera_a;
	chimera_a.n = n;
	chimera_a.framebuffers = framebuffers;
	g_bridge(CHIMERA_GL_OP_glDeleteFramebuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteProgram(GLuint program)
{
	struct ChimeraGlArgs_glDeleteProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glDeleteProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteQueries(GLsizei n, const GLuint * ids)
{
	struct ChimeraGlArgs_glDeleteQueries chimera_a;
	chimera_a.n = n;
	chimera_a.ids = ids;
	g_bridge(CHIMERA_GL_OP_glDeleteQueries, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteRenderbuffers(GLsizei n, const GLuint * renderbuffers)
{
	struct ChimeraGlArgs_glDeleteRenderbuffers chimera_a;
	chimera_a.n = n;
	chimera_a.renderbuffers = renderbuffers;
	g_bridge(CHIMERA_GL_OP_glDeleteRenderbuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteSamplers(GLsizei count, const GLuint * samplers)
{
	struct ChimeraGlArgs_glDeleteSamplers chimera_a;
	chimera_a.count = count;
	chimera_a.samplers = samplers;
	g_bridge(CHIMERA_GL_OP_glDeleteSamplers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteShader(GLuint shader)
{
	struct ChimeraGlArgs_glDeleteShader chimera_a;
	chimera_a.shader = shader;
	g_bridge(CHIMERA_GL_OP_glDeleteShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteSync(GLsync sync)
{
	struct ChimeraGlArgs_glDeleteSync chimera_a;
	chimera_a.sync = sync;
	g_bridge(CHIMERA_GL_OP_glDeleteSync, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteTextures(GLsizei n, const GLuint * textures)
{
	struct ChimeraGlArgs_glDeleteTextures chimera_a;
	chimera_a.n = n;
	chimera_a.textures = textures;
	g_bridge(CHIMERA_GL_OP_glDeleteTextures, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteVertexArrays(GLsizei n, const GLuint * arrays)
{
	struct ChimeraGlArgs_glDeleteVertexArrays chimera_a;
	chimera_a.n = n;
	chimera_a.arrays = arrays;
	g_bridge(CHIMERA_GL_OP_glDeleteVertexArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDepthFunc(GLenum func)
{
	struct ChimeraGlArgs_glDepthFunc chimera_a;
	chimera_a.func = func;
	g_bridge(CHIMERA_GL_OP_glDepthFunc, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDepthMask(GLboolean flag)
{
	struct ChimeraGlArgs_glDepthMask chimera_a;
	chimera_a.flag = flag;
	g_bridge(CHIMERA_GL_OP_glDepthMask, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDetachShader(GLuint program, GLuint shader)
{
	struct ChimeraGlArgs_glDetachShader chimera_a;
	chimera_a.program = program;
	chimera_a.shader = shader;
	g_bridge(CHIMERA_GL_OP_glDetachShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDisable(GLenum cap)
{
	struct ChimeraGlArgs_glDisable chimera_a;
	chimera_a.cap = cap;
	g_bridge(CHIMERA_GL_OP_glDisable, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDisableVertexAttribArray(GLuint index)
{
	struct ChimeraGlArgs_glDisableVertexAttribArray chimera_a;
	chimera_a.index = index;
	g_bridge(CHIMERA_GL_OP_glDisableVertexAttribArray, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDispatchCompute(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
{
	struct ChimeraGlArgs_glDispatchCompute chimera_a;
	chimera_a.num_groups_x = num_groups_x;
	chimera_a.num_groups_y = num_groups_y;
	chimera_a.num_groups_z = num_groups_z;
	g_bridge(CHIMERA_GL_OP_glDispatchCompute, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
	struct ChimeraGlArgs_glDrawArrays chimera_a;
	chimera_a.mode = mode;
	chimera_a.first = first;
	chimera_a.count = count;
	g_bridge(CHIMERA_GL_OP_glDrawArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDrawBuffers(GLsizei n, const GLenum * bufs)
{
	struct ChimeraGlArgs_glDrawBuffers chimera_a;
	chimera_a.n = n;
	chimera_a.bufs = bufs;
	g_bridge(CHIMERA_GL_OP_glDrawBuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDrawElements(GLenum mode, GLsizei count, GLenum type, const void * indices)
{
	struct ChimeraGlArgs_glDrawElements chimera_a;
	chimera_a.mode = mode;
	chimera_a.count = count;
	chimera_a.type = type;
	chimera_a.indices = indices;
	g_bridge(CHIMERA_GL_OP_glDrawElements, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDrawElementsBaseVertex(GLenum mode, GLsizei count, GLenum type, const void * indices, GLint basevertex)
{
	struct ChimeraGlArgs_glDrawElementsBaseVertex chimera_a;
	chimera_a.mode = mode;
	chimera_a.count = count;
	chimera_a.type = type;
	chimera_a.indices = indices;
	chimera_a.basevertex = basevertex;
	g_bridge(CHIMERA_GL_OP_glDrawElementsBaseVertex, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glEnable(GLenum cap)
{
	struct ChimeraGlArgs_glEnable chimera_a;
	chimera_a.cap = cap;
	g_bridge(CHIMERA_GL_OP_glEnable, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glEnableVertexAttribArray(GLuint index)
{
	struct ChimeraGlArgs_glEnableVertexAttribArray chimera_a;
	chimera_a.index = index;
	g_bridge(CHIMERA_GL_OP_glEnableVertexAttribArray, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glEndQuery(GLenum target)
{
	struct ChimeraGlArgs_glEndQuery chimera_a;
	chimera_a.target = target;
	g_bridge(CHIMERA_GL_OP_glEndQuery, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLsync GLAD_API_PTR w_glFenceSync(GLenum condition, GLbitfield flags)
{
	struct ChimeraGlArgs_glFenceSync chimera_a;
	chimera_a.condition = condition;
	chimera_a.flags = flags;
	return (GLsync)g_bridge(CHIMERA_GL_OP_glFenceSync, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFlushMappedBufferRange(GLenum target, GLintptr offset, GLsizeiptr length)
{
	struct ChimeraGlArgs_glFlushMappedBufferRange chimera_a;
	chimera_a.target = target;
	chimera_a.offset = offset;
	chimera_a.length = length;
	g_bridge(CHIMERA_GL_OP_glFlushMappedBufferRange, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
{
	struct ChimeraGlArgs_glFramebufferRenderbuffer chimera_a;
	chimera_a.target = target;
	chimera_a.attachment = attachment;
	chimera_a.renderbuffertarget = renderbuffertarget;
	chimera_a.renderbuffer = renderbuffer;
	g_bridge(CHIMERA_GL_OP_glFramebufferRenderbuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
{
	struct ChimeraGlArgs_glFramebufferTexture2D chimera_a;
	chimera_a.target = target;
	chimera_a.attachment = attachment;
	chimera_a.textarget = textarget;
	chimera_a.texture = texture;
	chimera_a.level = level;
	g_bridge(CHIMERA_GL_OP_glFramebufferTexture2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenBuffers(GLsizei n, GLuint * buffers)
{
	struct ChimeraGlArgs_glGenBuffers chimera_a;
	chimera_a.n = n;
	chimera_a.buffers = buffers;
	g_bridge(CHIMERA_GL_OP_glGenBuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenerateMipmap(GLenum target)
{
	struct ChimeraGlArgs_glGenerateMipmap chimera_a;
	chimera_a.target = target;
	g_bridge(CHIMERA_GL_OP_glGenerateMipmap, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenerateTextureMipmap(GLuint texture)
{
	struct ChimeraGlArgs_glGenerateTextureMipmap chimera_a;
	chimera_a.texture = texture;
	g_bridge(CHIMERA_GL_OP_glGenerateTextureMipmap, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenFramebuffers(GLsizei n, GLuint * framebuffers)
{
	struct ChimeraGlArgs_glGenFramebuffers chimera_a;
	chimera_a.n = n;
	chimera_a.framebuffers = framebuffers;
	g_bridge(CHIMERA_GL_OP_glGenFramebuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenQueries(GLsizei n, GLuint * ids)
{
	struct ChimeraGlArgs_glGenQueries chimera_a;
	chimera_a.n = n;
	chimera_a.ids = ids;
	g_bridge(CHIMERA_GL_OP_glGenQueries, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenRenderbuffers(GLsizei n, GLuint * renderbuffers)
{
	struct ChimeraGlArgs_glGenRenderbuffers chimera_a;
	chimera_a.n = n;
	chimera_a.renderbuffers = renderbuffers;
	g_bridge(CHIMERA_GL_OP_glGenRenderbuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenSamplers(GLsizei count, GLuint * samplers)
{
	struct ChimeraGlArgs_glGenSamplers chimera_a;
	chimera_a.count = count;
	chimera_a.samplers = samplers;
	g_bridge(CHIMERA_GL_OP_glGenSamplers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenTextures(GLsizei n, GLuint * textures)
{
	struct ChimeraGlArgs_glGenTextures chimera_a;
	chimera_a.n = n;
	chimera_a.textures = textures;
	g_bridge(CHIMERA_GL_OP_glGenTextures, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenVertexArrays(GLsizei n, GLuint * arrays)
{
	struct ChimeraGlArgs_glGenVertexArrays chimera_a;
	chimera_a.n = n;
	chimera_a.arrays = arrays;
	g_bridge(CHIMERA_GL_OP_glGenVertexArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLenum GLAD_API_PTR w_glGetError(void)
{
	return (GLenum)g_bridge(CHIMERA_GL_OP_glGetError, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetFloatv(GLenum pname, GLfloat * data)
{
	struct ChimeraGlArgs_glGetFloatv chimera_a;
	chimera_a.pname = pname;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glGetFloatv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetIntegerv(GLenum pname, GLint * data)
{
	struct ChimeraGlArgs_glGetIntegerv chimera_a;
	chimera_a.pname = pname;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glGetIntegerv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetProgramBinary(GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, void * binary)
{
	struct ChimeraGlArgs_glGetProgramBinary chimera_a;
	chimera_a.program = program;
	chimera_a.bufSize = bufSize;
	chimera_a.length = length;
	chimera_a.binaryFormat = binaryFormat;
	chimera_a.binary = binary;
	g_bridge(CHIMERA_GL_OP_glGetProgramBinary, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
{
	struct ChimeraGlArgs_glGetProgramInfoLog chimera_a;
	chimera_a.program = program;
	chimera_a.bufSize = bufSize;
	chimera_a.length = length;
	chimera_a.infoLog = infoLog;
	g_bridge(CHIMERA_GL_OP_glGetProgramInfoLog, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetProgramiv(GLuint program, GLenum pname, GLint * params)
{
	struct ChimeraGlArgs_glGetProgramiv chimera_a;
	chimera_a.program = program;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetProgramiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetQueryObjectiv(GLuint id, GLenum pname, GLint * params)
{
	struct ChimeraGlArgs_glGetQueryObjectiv chimera_a;
	chimera_a.id = id;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetQueryObjectiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetQueryObjectui64v(GLuint id, GLenum pname, GLuint64 * params)
{
	struct ChimeraGlArgs_glGetQueryObjectui64v chimera_a;
	chimera_a.id = id;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetQueryObjectui64v, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
{
	struct ChimeraGlArgs_glGetShaderInfoLog chimera_a;
	chimera_a.shader = shader;
	chimera_a.bufSize = bufSize;
	chimera_a.length = length;
	chimera_a.infoLog = infoLog;
	g_bridge(CHIMERA_GL_OP_glGetShaderInfoLog, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetShaderiv(GLuint shader, GLenum pname, GLint * params)
{
	struct ChimeraGlArgs_glGetShaderiv chimera_a;
	chimera_a.shader = shader;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetShaderiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision)
{
	struct ChimeraGlArgs_glGetShaderPrecisionFormat chimera_a;
	chimera_a.shadertype = shadertype;
	chimera_a.precisiontype = precisiontype;
	chimera_a.range = range;
	chimera_a.precision = precision;
	g_bridge(CHIMERA_GL_OP_glGetShaderPrecisionFormat, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static const GLubyte *GLAD_API_PTR w_glGetString(GLenum name)
{
	static char buffer[4096];
	struct ChimeraGlArgs_glGetString chimera_a;
	chimera_a.name = name;
	g_bridge(CHIMERA_GL_OP_glGetString, (uint64_t)(uintptr_t)&chimera_a,
		(uint64_t)(uintptr_t)buffer, sizeof buffer, 0, 0);
	return buffer[0] ? (const GLubyte *)buffer : NULL;
}

static const GLubyte *GLAD_API_PTR w_glGetStringi(GLenum name, GLuint index)
{
	static char buffer[4096];
	struct ChimeraGlArgs_glGetStringi chimera_a;
	chimera_a.name = name;
	chimera_a.index = index;
	g_bridge(CHIMERA_GL_OP_glGetStringi, (uint64_t)(uintptr_t)&chimera_a,
		(uint64_t)(uintptr_t)buffer, sizeof buffer, 0, 0);
	return buffer[0] ? (const GLubyte *)buffer : NULL;
}

static void GLAD_API_PTR w_glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, void * pixels)
{
	struct ChimeraGlArgs_glGetTexImage chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glGetTexImage, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetTextureImage(GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, void * pixels)
{
	struct ChimeraGlArgs_glGetTextureImage chimera_a;
	chimera_a.texture = texture;
	chimera_a.level = level;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.bufSize = bufSize;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glGetTextureImage, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLuint GLAD_API_PTR w_glGetUniformBlockIndex(GLuint program, const GLchar * uniformBlockName)
{
	struct ChimeraGlArgs_glGetUniformBlockIndex chimera_a;
	chimera_a.program = program;
	chimera_a.uniformBlockName = uniformBlockName;
	return (GLuint)g_bridge(CHIMERA_GL_OP_glGetUniformBlockIndex, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLint GLAD_API_PTR w_glGetUniformLocation(GLuint program, const GLchar * name)
{
	struct ChimeraGlArgs_glGetUniformLocation chimera_a;
	chimera_a.program = program;
	chimera_a.name = name;
	return (GLint)g_bridge(CHIMERA_GL_OP_glGetUniformLocation, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glHint(GLenum target, GLenum mode)
{
	struct ChimeraGlArgs_glHint chimera_a;
	chimera_a.target = target;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glHint, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glInvalidateFramebuffer(GLenum target, GLsizei numAttachments, const GLenum * attachments)
{
	struct ChimeraGlArgs_glInvalidateFramebuffer chimera_a;
	chimera_a.target = target;
	chimera_a.numAttachments = numAttachments;
	chimera_a.attachments = attachments;
	g_bridge(CHIMERA_GL_OP_glInvalidateFramebuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glLineWidth(GLfloat width)
{
	struct ChimeraGlArgs_glLineWidth chimera_a;
	chimera_a.width = width;
	g_bridge(CHIMERA_GL_OP_glLineWidth, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glLinkProgram(GLuint program)
{
	struct ChimeraGlArgs_glLinkProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glLinkProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void * GLAD_API_PTR w_glMapBufferRange(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
{
	struct ChimeraGlArgs_glMapBufferRange chimera_a;
	chimera_a.target = target;
	chimera_a.offset = offset;
	chimera_a.length = length;
	chimera_a.access = access;
	return (void *)g_bridge(CHIMERA_GL_OP_glMapBufferRange, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glMemoryBarrier(GLbitfield barriers)
{
	struct ChimeraGlArgs_glMemoryBarrier chimera_a;
	chimera_a.barriers = barriers;
	g_bridge(CHIMERA_GL_OP_glMemoryBarrier, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPixelStorei(GLenum pname, GLint param)
{
	struct ChimeraGlArgs_glPixelStorei chimera_a;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glPixelStorei, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPolygonMode(GLenum face, GLenum mode)
{
	struct ChimeraGlArgs_glPolygonMode chimera_a;
	chimera_a.face = face;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glPolygonMode, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPrimitiveRestartIndex(GLuint index)
{
	struct ChimeraGlArgs_glPrimitiveRestartIndex chimera_a;
	chimera_a.index = index;
	g_bridge(CHIMERA_GL_OP_glPrimitiveRestartIndex, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProgramBinary(GLuint program, GLenum binaryFormat, const void * binary, GLsizei length)
{
	struct ChimeraGlArgs_glProgramBinary chimera_a;
	chimera_a.program = program;
	chimera_a.binaryFormat = binaryFormat;
	chimera_a.binary = binary;
	chimera_a.length = length;
	g_bridge(CHIMERA_GL_OP_glProgramBinary, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProgramParameteri(GLuint program, GLenum pname, GLint value)
{
	struct ChimeraGlArgs_glProgramParameteri chimera_a;
	chimera_a.program = program;
	chimera_a.pname = pname;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glProgramParameteri, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glReadBuffer(GLenum src)
{
	struct ChimeraGlArgs_glReadBuffer chimera_a;
	chimera_a.src = src;
	g_bridge(CHIMERA_GL_OP_glReadBuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void * pixels)
{
	struct ChimeraGlArgs_glReadPixels chimera_a;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glReadPixels, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glRenderbufferStorage chimera_a;
	chimera_a.target = target;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glRenderbufferStorage, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param)
{
	struct ChimeraGlArgs_glSamplerParameterf chimera_a;
	chimera_a.sampler = sampler;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glSamplerParameterf, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glSamplerParameteri(GLuint sampler, GLenum pname, GLint param)
{
	struct ChimeraGlArgs_glSamplerParameteri chimera_a;
	chimera_a.sampler = sampler;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glSamplerParameteri, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glScissor chimera_a;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glScissor, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glScissorIndexed(GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glScissorIndexed chimera_a;
	chimera_a.index = index;
	chimera_a.left = left;
	chimera_a.bottom = bottom;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glScissorIndexed, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glShaderSource(GLuint shader, GLsizei count, const GLchar *const* string, const GLint * length)
{
	struct ChimeraGlArgs_glShaderSource chimera_a;
	chimera_a.shader = shader;
	chimera_a.count = count;
	chimera_a.string = string;
	chimera_a.length = length;
	g_bridge(CHIMERA_GL_OP_glShaderSource, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
	struct ChimeraGlArgs_glStencilFunc chimera_a;
	chimera_a.func = func;
	chimera_a.ref = ref;
	chimera_a.mask = mask;
	g_bridge(CHIMERA_GL_OP_glStencilFunc, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glStencilMask(GLuint mask)
{
	struct ChimeraGlArgs_glStencilMask chimera_a;
	chimera_a.mask = mask;
	g_bridge(CHIMERA_GL_OP_glStencilMask, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
	struct ChimeraGlArgs_glStencilOp chimera_a;
	chimera_a.fail = fail;
	chimera_a.zfail = zfail;
	chimera_a.zpass = zpass;
	g_bridge(CHIMERA_GL_OP_glStencilOp, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void * pixels)
{
	struct ChimeraGlArgs_glTexImage2D chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.border = border;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glTexImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
	struct ChimeraGlArgs_glTexParameterf chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glTexParameterf, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameterfv(GLenum target, GLenum pname, const GLfloat * params)
{
	struct ChimeraGlArgs_glTexParameterfv chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glTexParameterfv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameteri(GLenum target, GLenum pname, GLint param)
{
	struct ChimeraGlArgs_glTexParameteri chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glTexParameteri, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glTexStorage2D chimera_a;
	chimera_a.target = target;
	chimera_a.levels = levels;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glTexStorage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void * pixels)
{
	struct ChimeraGlArgs_glTexSubImage2D chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.xoffset = xoffset;
	chimera_a.yoffset = yoffset;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glTexSubImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTextureBarrier(void)
{
	g_bridge(CHIMERA_GL_OP_glTextureBarrier, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTextureBarrierNV(void)
{
	g_bridge(CHIMERA_GL_OP_glTextureBarrierNV, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTextureParameteri(GLuint texture, GLenum pname, GLint param)
{
	struct ChimeraGlArgs_glTextureParameteri chimera_a;
	chimera_a.texture = texture;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glTextureParameteri, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTextureStorage2D(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glTextureStorage2D chimera_a;
	chimera_a.texture = texture;
	chimera_a.levels = levels;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glTextureStorage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTextureSubImage2D(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void * pixels)
{
	struct ChimeraGlArgs_glTextureSubImage2D chimera_a;
	chimera_a.texture = texture;
	chimera_a.level = level;
	chimera_a.xoffset = xoffset;
	chimera_a.yoffset = yoffset;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glTextureSubImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1f(GLint location, GLfloat v0)
{
	struct ChimeraGlArgs_glUniform1f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glUniform1f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1i(GLint location, GLint v0)
{
	struct ChimeraGlArgs_glUniform1i chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glUniform1i, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1ui(GLint location, GLuint v0)
{
	struct ChimeraGlArgs_glUniform1ui chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glUniform1ui, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2f(GLint location, GLfloat v0, GLfloat v1)
{
	struct ChimeraGlArgs_glUniform2f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	g_bridge(CHIMERA_GL_OP_glUniform2f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform2fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform2fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2i(GLint location, GLint v0, GLint v1)
{
	struct ChimeraGlArgs_glUniform2i chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	g_bridge(CHIMERA_GL_OP_glUniform2i, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2iv(GLint location, GLsizei count, const GLint * value)
{
	struct ChimeraGlArgs_glUniform2iv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform2iv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2ui(GLint location, GLuint v0, GLuint v1)
{
	struct ChimeraGlArgs_glUniform2ui chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	g_bridge(CHIMERA_GL_OP_glUniform2ui, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2uiv(GLint location, GLsizei count, const GLuint * value)
{
	struct ChimeraGlArgs_glUniform2uiv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform2uiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
{
	struct ChimeraGlArgs_glUniform3f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	g_bridge(CHIMERA_GL_OP_glUniform3f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform3fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform3fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3i(GLint location, GLint v0, GLint v1, GLint v2)
{
	struct ChimeraGlArgs_glUniform3i chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	g_bridge(CHIMERA_GL_OP_glUniform3i, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3iv(GLint location, GLsizei count, const GLint * value)
{
	struct ChimeraGlArgs_glUniform3iv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform3iv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3ui(GLint location, GLuint v0, GLuint v1, GLuint v2)
{
	struct ChimeraGlArgs_glUniform3ui chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	g_bridge(CHIMERA_GL_OP_glUniform3ui, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3uiv(GLint location, GLsizei count, const GLuint * value)
{
	struct ChimeraGlArgs_glUniform3uiv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform3uiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
{
	struct ChimeraGlArgs_glUniform4f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	chimera_a.v3 = v3;
	g_bridge(CHIMERA_GL_OP_glUniform4f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform4fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform4fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3)
{
	struct ChimeraGlArgs_glUniform4i chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	chimera_a.v3 = v3;
	g_bridge(CHIMERA_GL_OP_glUniform4i, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4iv(GLint location, GLsizei count, const GLint * value)
{
	struct ChimeraGlArgs_glUniform4iv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform4iv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4ui(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
{
	struct ChimeraGlArgs_glUniform4ui chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	chimera_a.v3 = v3;
	g_bridge(CHIMERA_GL_OP_glUniform4ui, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4uiv(GLint location, GLsizei count, const GLuint * value)
{
	struct ChimeraGlArgs_glUniform4uiv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform4uiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
{
	struct ChimeraGlArgs_glUniformBlockBinding chimera_a;
	chimera_a.program = program;
	chimera_a.uniformBlockIndex = uniformBlockIndex;
	chimera_a.uniformBlockBinding = uniformBlockBinding;
	g_bridge(CHIMERA_GL_OP_glUniformBlockBinding, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniformMatrix2fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.transpose = transpose;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniformMatrix2fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniformMatrix3fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.transpose = transpose;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniformMatrix3fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniformMatrix4fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.transpose = transpose;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniformMatrix4fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLboolean GLAD_API_PTR w_glUnmapBuffer(GLenum target)
{
	struct ChimeraGlArgs_glUnmapBuffer chimera_a;
	chimera_a.target = target;
	return (GLboolean)g_bridge(CHIMERA_GL_OP_glUnmapBuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUseProgram(GLuint program)
{
	struct ChimeraGlArgs_glUseProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glUseProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void * pointer)
{
	struct ChimeraGlArgs_glVertexAttribIPointer chimera_a;
	chimera_a.index = index;
	chimera_a.size = size;
	chimera_a.type = type;
	chimera_a.stride = stride;
	chimera_a.pointer = pointer;
	g_bridge(CHIMERA_GL_OP_glVertexAttribIPointer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer)
{
	struct ChimeraGlArgs_glVertexAttribPointer chimera_a;
	chimera_a.index = index;
	chimera_a.size = size;
	chimera_a.type = type;
	chimera_a.normalized = normalized;
	chimera_a.stride = stride;
	chimera_a.pointer = pointer;
	g_bridge(CHIMERA_GL_OP_glVertexAttribPointer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glViewport chimera_a;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glViewport, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glViewportIndexedf(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h)
{
	struct ChimeraGlArgs_glViewportIndexedf chimera_a;
	chimera_a.index = index;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.w = w;
	chimera_a.h = h;
	g_bridge(CHIMERA_GL_OP_glViewportIndexedf, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendEquation(GLenum mode)
{
	struct ChimeraGlArgs_glBlendEquation chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glBlendEquation, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearDepth(GLdouble depth)
{
	struct ChimeraGlArgs_glClearDepth chimera_a;
	chimera_a.depth = depth;
	g_bridge(CHIMERA_GL_OP_glClearDepth, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDebugMessageInsert(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * buf)
{
	struct ChimeraGlArgs_glDebugMessageInsert chimera_a;
	chimera_a.source = source;
	chimera_a.type = type;
	chimera_a.id = id;
	chimera_a.severity = severity;
	chimera_a.length = length;
	chimera_a.buf = buf;
	g_bridge(CHIMERA_GL_OP_glDebugMessageInsert, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFinish(void)
{
	g_bridge(CHIMERA_GL_OP_glFinish, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFrameTerminatorGREMEDY(void)
{
	g_bridge(CHIMERA_GL_OP_glFrameTerminatorGREMEDY, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFrontFace(GLenum mode)
{
	struct ChimeraGlArgs_glFrontFace chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glFrontFace, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint * params)
{
	struct ChimeraGlArgs_glGetQueryObjectuiv chimera_a;
	chimera_a.id = id;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetQueryObjectuiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glMultiDrawArrays(GLenum mode, const GLint * first, const GLsizei * count, GLsizei drawcount)
{
	struct ChimeraGlArgs_glMultiDrawArrays chimera_a;
	chimera_a.mode = mode;
	chimera_a.first = first;
	chimera_a.count = count;
	chimera_a.drawcount = drawcount;
	g_bridge(CHIMERA_GL_OP_glMultiDrawArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glObjectLabel(GLenum identifier, GLuint name, GLsizei length, const GLchar * label)
{
	struct ChimeraGlArgs_glObjectLabel chimera_a;
	chimera_a.identifier = identifier;
	chimera_a.name = name;
	chimera_a.length = length;
	chimera_a.label = label;
	g_bridge(CHIMERA_GL_OP_glObjectLabel, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPopDebugGroup(void)
{
	g_bridge(CHIMERA_GL_OP_glPopDebugGroup, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProgramUniform1i(GLuint program, GLint location, GLint v0)
{
	struct ChimeraGlArgs_glProgramUniform1i chimera_a;
	chimera_a.program = program;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glProgramUniform1i, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProgramUniform2f(GLuint program, GLint location, GLfloat v0, GLfloat v1)
{
	struct ChimeraGlArgs_glProgramUniform2f chimera_a;
	chimera_a.program = program;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	g_bridge(CHIMERA_GL_OP_glProgramUniform2f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProvokingVertex(GLenum mode)
{
	struct ChimeraGlArgs_glProvokingVertex chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glProvokingVertex, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPushDebugGroup(GLenum source, GLuint id, GLsizei length, const GLchar * message)
{
	struct ChimeraGlArgs_glPushDebugGroup chimera_a;
	chimera_a.source = source;
	chimera_a.id = id;
	chimera_a.length = length;
	chimera_a.message = message;
	g_bridge(CHIMERA_GL_OP_glPushDebugGroup, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void * pixels)
{
	struct ChimeraGlArgs_glTexImage3D chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.depth = depth;
	chimera_a.border = border;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glTexImage3D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameteriv(GLenum target, GLenum pname, const GLint * params)
{
	struct ChimeraGlArgs_glTexParameteriv chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glTexParameteriv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform1fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform1fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1iv(GLint location, GLsizei count, const GLint * value)
{
	struct ChimeraGlArgs_glUniform1iv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform1iv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1uiv(GLint location, GLsizei count, const GLuint * value)
{
	struct ChimeraGlArgs_glUniform1uiv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform1uiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glValidateProgram(GLuint program)
{
	struct ChimeraGlArgs_glValidateProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glValidateProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glVertexAttrib4fv(GLuint index, const GLfloat * v)
{
	struct ChimeraGlArgs_glVertexAttrib4fv chimera_a;
	chimera_a.index = index;
	chimera_a.v = v;
	g_bridge(CHIMERA_GL_OP_glVertexAttrib4fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

/* Returns false when the host is older than this guest - it would not know
 * every opcode this guest can emit, and the core must draw some other way. */
bool chimera_gl_install(chimera_gl_bridge_fn bridge)
{
	uint64_t host_length = bridge(GL_OP_LIST_LENGTH, 0, 0, 0, 0, 0);
	if (host_length < CHIMERA_GL_OP_LIST_LENGTH)
	{
		fprintf(stderr, "chimera gl: the host knows %llu entry points and this "
			"core was built against %d; not bridging\n",
			(unsigned long long)host_length, CHIMERA_GL_OP_LIST_LENGTH);
		return false;
	}

	g_bridge = bridge;
	glad_glActiveTexture = w_glActiveTexture;
	glad_glAttachShader = w_glAttachShader;
	glad_glBeginQuery = w_glBeginQuery;
	glad_glBindAttribLocation = w_glBindAttribLocation;
	glad_glBindBuffer = w_glBindBuffer;
	glad_glBindBufferRange = w_glBindBufferRange;
	glad_glBindFragDataLocation = w_glBindFragDataLocation;
	glad_glBindFragDataLocationIndexed = w_glBindFragDataLocationIndexed;
	glad_glBindFragDataLocationIndexedEXT = w_glBindFragDataLocationIndexedEXT;
	glad_glBindFramebuffer = w_glBindFramebuffer;
	glad_glBindImageTexture = w_glBindImageTexture;
	glad_glBindRenderbuffer = w_glBindRenderbuffer;
	glad_glBindSampler = w_glBindSampler;
	glad_glBindTexture = w_glBindTexture;
	glad_glBindTextureUnit = w_glBindTextureUnit;
	glad_glBindVertexArray = w_glBindVertexArray;
	glad_glBlendColor = w_glBlendColor;
	glad_glBlendEquationSeparate = w_glBlendEquationSeparate;
	glad_glBlendFunc = w_glBlendFunc;
	glad_glBlendFuncSeparate = w_glBlendFuncSeparate;
	glad_glBlitFramebuffer = w_glBlitFramebuffer;
	glad_glBufferData = w_glBufferData;
	glad_glBufferStorage = w_glBufferStorage;
	glad_glBufferStorageEXT = w_glBufferStorageEXT;
	glad_glBufferSubData = w_glBufferSubData;
	glad_glCheckFramebufferStatus = w_glCheckFramebufferStatus;
	glad_glClear = w_glClear;
	glad_glClearBufferfv = w_glClearBufferfv;
	glad_glClearBufferiv = w_glClearBufferiv;
	glad_glClearBufferuiv = w_glClearBufferuiv;
	glad_glClearColor = w_glClearColor;
	glad_glClearDepthf = w_glClearDepthf;
	glad_glClearStencil = w_glClearStencil;
	glad_glClientWaitSync = w_glClientWaitSync;
	glad_glClipControl = w_glClipControl;
	glad_glColorMask = w_glColorMask;
	glad_glColorMaski = w_glColorMaski;
	glad_glCompileShader = w_glCompileShader;
	glad_glCompressedTexSubImage2D = w_glCompressedTexSubImage2D;
	glad_glCompressedTextureSubImage2D = w_glCompressedTextureSubImage2D;
	glad_glCopyImageSubData = w_glCopyImageSubData;
	glad_glCopyImageSubDataEXT = w_glCopyImageSubDataEXT;
	glad_glCopyImageSubDataNV = w_glCopyImageSubDataNV;
	glad_glCopyTexSubImage2D = w_glCopyTexSubImage2D;
	glad_glCopyTextureSubImage2D = w_glCopyTextureSubImage2D;
	glad_glCreateProgram = w_glCreateProgram;
	glad_glCreateSamplers = w_glCreateSamplers;
	glad_glCreateShader = w_glCreateShader;
	glad_glCreateTextures = w_glCreateTextures;
	glad_glCullFace = w_glCullFace;
	glad_glDebugMessageCallback = w_glDebugMessageCallback;
	glad_glDebugMessageControl = w_glDebugMessageControl;
	glad_glDeleteBuffers = w_glDeleteBuffers;
	glad_glDeleteFramebuffers = w_glDeleteFramebuffers;
	glad_glDeleteProgram = w_glDeleteProgram;
	glad_glDeleteQueries = w_glDeleteQueries;
	glad_glDeleteRenderbuffers = w_glDeleteRenderbuffers;
	glad_glDeleteSamplers = w_glDeleteSamplers;
	glad_glDeleteShader = w_glDeleteShader;
	glad_glDeleteSync = w_glDeleteSync;
	glad_glDeleteTextures = w_glDeleteTextures;
	glad_glDeleteVertexArrays = w_glDeleteVertexArrays;
	glad_glDepthFunc = w_glDepthFunc;
	glad_glDepthMask = w_glDepthMask;
	glad_glDetachShader = w_glDetachShader;
	glad_glDisable = w_glDisable;
	glad_glDisableVertexAttribArray = w_glDisableVertexAttribArray;
	glad_glDispatchCompute = w_glDispatchCompute;
	glad_glDrawArrays = w_glDrawArrays;
	glad_glDrawBuffers = w_glDrawBuffers;
	glad_glDrawElements = w_glDrawElements;
	glad_glDrawElementsBaseVertex = w_glDrawElementsBaseVertex;
	glad_glEnable = w_glEnable;
	glad_glEnableVertexAttribArray = w_glEnableVertexAttribArray;
	glad_glEndQuery = w_glEndQuery;
	glad_glFenceSync = w_glFenceSync;
	glad_glFlushMappedBufferRange = w_glFlushMappedBufferRange;
	glad_glFramebufferRenderbuffer = w_glFramebufferRenderbuffer;
	glad_glFramebufferTexture2D = w_glFramebufferTexture2D;
	glad_glGenBuffers = w_glGenBuffers;
	glad_glGenerateMipmap = w_glGenerateMipmap;
	glad_glGenerateTextureMipmap = w_glGenerateTextureMipmap;
	glad_glGenFramebuffers = w_glGenFramebuffers;
	glad_glGenQueries = w_glGenQueries;
	glad_glGenRenderbuffers = w_glGenRenderbuffers;
	glad_glGenSamplers = w_glGenSamplers;
	glad_glGenTextures = w_glGenTextures;
	glad_glGenVertexArrays = w_glGenVertexArrays;
	glad_glGetError = w_glGetError;
	glad_glGetFloatv = w_glGetFloatv;
	glad_glGetIntegerv = w_glGetIntegerv;
	glad_glGetProgramBinary = w_glGetProgramBinary;
	glad_glGetProgramInfoLog = w_glGetProgramInfoLog;
	glad_glGetProgramiv = w_glGetProgramiv;
	glad_glGetQueryObjectiv = w_glGetQueryObjectiv;
	glad_glGetQueryObjectui64v = w_glGetQueryObjectui64v;
	glad_glGetShaderInfoLog = w_glGetShaderInfoLog;
	glad_glGetShaderiv = w_glGetShaderiv;
	glad_glGetShaderPrecisionFormat = w_glGetShaderPrecisionFormat;
	glad_glGetString = w_glGetString;
	glad_glGetStringi = w_glGetStringi;
	glad_glGetTexImage = w_glGetTexImage;
	glad_glGetTextureImage = w_glGetTextureImage;
	glad_glGetUniformBlockIndex = w_glGetUniformBlockIndex;
	glad_glGetUniformLocation = w_glGetUniformLocation;
	glad_glHint = w_glHint;
	glad_glInvalidateFramebuffer = w_glInvalidateFramebuffer;
	glad_glLineWidth = w_glLineWidth;
	glad_glLinkProgram = w_glLinkProgram;
	glad_glMapBufferRange = w_glMapBufferRange;
	glad_glMemoryBarrier = w_glMemoryBarrier;
	glad_glPixelStorei = w_glPixelStorei;
	glad_glPolygonMode = w_glPolygonMode;
	glad_glPrimitiveRestartIndex = w_glPrimitiveRestartIndex;
	glad_glProgramBinary = w_glProgramBinary;
	glad_glProgramParameteri = w_glProgramParameteri;
	glad_glReadBuffer = w_glReadBuffer;
	glad_glReadPixels = w_glReadPixels;
	glad_glRenderbufferStorage = w_glRenderbufferStorage;
	glad_glSamplerParameterf = w_glSamplerParameterf;
	glad_glSamplerParameteri = w_glSamplerParameteri;
	glad_glScissor = w_glScissor;
	glad_glScissorIndexed = w_glScissorIndexed;
	glad_glShaderSource = w_glShaderSource;
	glad_glStencilFunc = w_glStencilFunc;
	glad_glStencilMask = w_glStencilMask;
	glad_glStencilOp = w_glStencilOp;
	glad_glTexImage2D = w_glTexImage2D;
	glad_glTexParameterf = w_glTexParameterf;
	glad_glTexParameterfv = w_glTexParameterfv;
	glad_glTexParameteri = w_glTexParameteri;
	glad_glTexStorage2D = w_glTexStorage2D;
	glad_glTexSubImage2D = w_glTexSubImage2D;
	glad_glTextureBarrier = w_glTextureBarrier;
	glad_glTextureBarrierNV = w_glTextureBarrierNV;
	glad_glTextureParameteri = w_glTextureParameteri;
	glad_glTextureStorage2D = w_glTextureStorage2D;
	glad_glTextureSubImage2D = w_glTextureSubImage2D;
	glad_glUniform1f = w_glUniform1f;
	glad_glUniform1i = w_glUniform1i;
	glad_glUniform1ui = w_glUniform1ui;
	glad_glUniform2f = w_glUniform2f;
	glad_glUniform2fv = w_glUniform2fv;
	glad_glUniform2i = w_glUniform2i;
	glad_glUniform2iv = w_glUniform2iv;
	glad_glUniform2ui = w_glUniform2ui;
	glad_glUniform2uiv = w_glUniform2uiv;
	glad_glUniform3f = w_glUniform3f;
	glad_glUniform3fv = w_glUniform3fv;
	glad_glUniform3i = w_glUniform3i;
	glad_glUniform3iv = w_glUniform3iv;
	glad_glUniform3ui = w_glUniform3ui;
	glad_glUniform3uiv = w_glUniform3uiv;
	glad_glUniform4f = w_glUniform4f;
	glad_glUniform4fv = w_glUniform4fv;
	glad_glUniform4i = w_glUniform4i;
	glad_glUniform4iv = w_glUniform4iv;
	glad_glUniform4ui = w_glUniform4ui;
	glad_glUniform4uiv = w_glUniform4uiv;
	glad_glUniformBlockBinding = w_glUniformBlockBinding;
	glad_glUniformMatrix2fv = w_glUniformMatrix2fv;
	glad_glUniformMatrix3fv = w_glUniformMatrix3fv;
	glad_glUniformMatrix4fv = w_glUniformMatrix4fv;
	glad_glUnmapBuffer = w_glUnmapBuffer;
	glad_glUseProgram = w_glUseProgram;
	glad_glVertexAttribIPointer = w_glVertexAttribIPointer;
	glad_glVertexAttribPointer = w_glVertexAttribPointer;
	glad_glViewport = w_glViewport;
	glad_glViewportIndexedf = w_glViewportIndexedf;
	glad_glBlendEquation = w_glBlendEquation;
	glad_glClearDepth = w_glClearDepth;
	glad_glDebugMessageInsert = w_glDebugMessageInsert;
	glad_glFinish = w_glFinish;
	glad_glFrameTerminatorGREMEDY = w_glFrameTerminatorGREMEDY;
	glad_glFrontFace = w_glFrontFace;
	glad_glGetQueryObjectuiv = w_glGetQueryObjectuiv;
	glad_glMultiDrawArrays = w_glMultiDrawArrays;
	glad_glObjectLabel = w_glObjectLabel;
	glad_glPopDebugGroup = w_glPopDebugGroup;
	glad_glProgramUniform1i = w_glProgramUniform1i;
	glad_glProgramUniform2f = w_glProgramUniform2f;
	glad_glProvokingVertex = w_glProvokingVertex;
	glad_glPushDebugGroup = w_glPushDebugGroup;
	glad_glTexImage3D = w_glTexImage3D;
	glad_glTexParameteriv = w_glTexParameteriv;
	glad_glUniform1fv = w_glUniform1fv;
	glad_glUniform1iv = w_glUniform1iv;
	glad_glUniform1uiv = w_glUniform1uiv;
	glad_glValidateProgram = w_glValidateProgram;
	glad_glVertexAttrib4fv = w_glVertexAttrib4fv;
	return true;
}

struct ChimeraGlEntry { const char *name; void *fn; };
static const struct ChimeraGlEntry g_entries[] = {
	{ "glActiveTexture", (void *)w_glActiveTexture },
	{ "glAttachShader", (void *)w_glAttachShader },
	{ "glBeginQuery", (void *)w_glBeginQuery },
	{ "glBindAttribLocation", (void *)w_glBindAttribLocation },
	{ "glBindBuffer", (void *)w_glBindBuffer },
	{ "glBindBufferRange", (void *)w_glBindBufferRange },
	{ "glBindFragDataLocation", (void *)w_glBindFragDataLocation },
	{ "glBindFragDataLocationIndexed", (void *)w_glBindFragDataLocationIndexed },
	{ "glBindFragDataLocationIndexedEXT", (void *)w_glBindFragDataLocationIndexedEXT },
	{ "glBindFramebuffer", (void *)w_glBindFramebuffer },
	{ "glBindImageTexture", (void *)w_glBindImageTexture },
	{ "glBindRenderbuffer", (void *)w_glBindRenderbuffer },
	{ "glBindSampler", (void *)w_glBindSampler },
	{ "glBindTexture", (void *)w_glBindTexture },
	{ "glBindTextureUnit", (void *)w_glBindTextureUnit },
	{ "glBindVertexArray", (void *)w_glBindVertexArray },
	{ "glBlendColor", (void *)w_glBlendColor },
	{ "glBlendEquationSeparate", (void *)w_glBlendEquationSeparate },
	{ "glBlendFunc", (void *)w_glBlendFunc },
	{ "glBlendFuncSeparate", (void *)w_glBlendFuncSeparate },
	{ "glBlitFramebuffer", (void *)w_glBlitFramebuffer },
	{ "glBufferData", (void *)w_glBufferData },
	{ "glBufferStorage", (void *)w_glBufferStorage },
	{ "glBufferStorageEXT", (void *)w_glBufferStorageEXT },
	{ "glBufferSubData", (void *)w_glBufferSubData },
	{ "glCheckFramebufferStatus", (void *)w_glCheckFramebufferStatus },
	{ "glClear", (void *)w_glClear },
	{ "glClearBufferfv", (void *)w_glClearBufferfv },
	{ "glClearBufferiv", (void *)w_glClearBufferiv },
	{ "glClearBufferuiv", (void *)w_glClearBufferuiv },
	{ "glClearColor", (void *)w_glClearColor },
	{ "glClearDepthf", (void *)w_glClearDepthf },
	{ "glClearStencil", (void *)w_glClearStencil },
	{ "glClientWaitSync", (void *)w_glClientWaitSync },
	{ "glClipControl", (void *)w_glClipControl },
	{ "glColorMask", (void *)w_glColorMask },
	{ "glColorMaski", (void *)w_glColorMaski },
	{ "glCompileShader", (void *)w_glCompileShader },
	{ "glCompressedTexSubImage2D", (void *)w_glCompressedTexSubImage2D },
	{ "glCompressedTextureSubImage2D", (void *)w_glCompressedTextureSubImage2D },
	{ "glCopyImageSubData", (void *)w_glCopyImageSubData },
	{ "glCopyImageSubDataEXT", (void *)w_glCopyImageSubDataEXT },
	{ "glCopyImageSubDataNV", (void *)w_glCopyImageSubDataNV },
	{ "glCopyTexSubImage2D", (void *)w_glCopyTexSubImage2D },
	{ "glCopyTextureSubImage2D", (void *)w_glCopyTextureSubImage2D },
	{ "glCreateProgram", (void *)w_glCreateProgram },
	{ "glCreateSamplers", (void *)w_glCreateSamplers },
	{ "glCreateShader", (void *)w_glCreateShader },
	{ "glCreateTextures", (void *)w_glCreateTextures },
	{ "glCullFace", (void *)w_glCullFace },
	{ "glDebugMessageCallback", (void *)w_glDebugMessageCallback },
	{ "glDebugMessageControl", (void *)w_glDebugMessageControl },
	{ "glDeleteBuffers", (void *)w_glDeleteBuffers },
	{ "glDeleteFramebuffers", (void *)w_glDeleteFramebuffers },
	{ "glDeleteProgram", (void *)w_glDeleteProgram },
	{ "glDeleteQueries", (void *)w_glDeleteQueries },
	{ "glDeleteRenderbuffers", (void *)w_glDeleteRenderbuffers },
	{ "glDeleteSamplers", (void *)w_glDeleteSamplers },
	{ "glDeleteShader", (void *)w_glDeleteShader },
	{ "glDeleteSync", (void *)w_glDeleteSync },
	{ "glDeleteTextures", (void *)w_glDeleteTextures },
	{ "glDeleteVertexArrays", (void *)w_glDeleteVertexArrays },
	{ "glDepthFunc", (void *)w_glDepthFunc },
	{ "glDepthMask", (void *)w_glDepthMask },
	{ "glDetachShader", (void *)w_glDetachShader },
	{ "glDisable", (void *)w_glDisable },
	{ "glDisableVertexAttribArray", (void *)w_glDisableVertexAttribArray },
	{ "glDispatchCompute", (void *)w_glDispatchCompute },
	{ "glDrawArrays", (void *)w_glDrawArrays },
	{ "glDrawBuffers", (void *)w_glDrawBuffers },
	{ "glDrawElements", (void *)w_glDrawElements },
	{ "glDrawElementsBaseVertex", (void *)w_glDrawElementsBaseVertex },
	{ "glEnable", (void *)w_glEnable },
	{ "glEnableVertexAttribArray", (void *)w_glEnableVertexAttribArray },
	{ "glEndQuery", (void *)w_glEndQuery },
	{ "glFenceSync", (void *)w_glFenceSync },
	{ "glFlushMappedBufferRange", (void *)w_glFlushMappedBufferRange },
	{ "glFramebufferRenderbuffer", (void *)w_glFramebufferRenderbuffer },
	{ "glFramebufferTexture2D", (void *)w_glFramebufferTexture2D },
	{ "glGenBuffers", (void *)w_glGenBuffers },
	{ "glGenerateMipmap", (void *)w_glGenerateMipmap },
	{ "glGenerateTextureMipmap", (void *)w_glGenerateTextureMipmap },
	{ "glGenFramebuffers", (void *)w_glGenFramebuffers },
	{ "glGenQueries", (void *)w_glGenQueries },
	{ "glGenRenderbuffers", (void *)w_glGenRenderbuffers },
	{ "glGenSamplers", (void *)w_glGenSamplers },
	{ "glGenTextures", (void *)w_glGenTextures },
	{ "glGenVertexArrays", (void *)w_glGenVertexArrays },
	{ "glGetError", (void *)w_glGetError },
	{ "glGetFloatv", (void *)w_glGetFloatv },
	{ "glGetIntegerv", (void *)w_glGetIntegerv },
	{ "glGetProgramBinary", (void *)w_glGetProgramBinary },
	{ "glGetProgramInfoLog", (void *)w_glGetProgramInfoLog },
	{ "glGetProgramiv", (void *)w_glGetProgramiv },
	{ "glGetQueryObjectiv", (void *)w_glGetQueryObjectiv },
	{ "glGetQueryObjectui64v", (void *)w_glGetQueryObjectui64v },
	{ "glGetShaderInfoLog", (void *)w_glGetShaderInfoLog },
	{ "glGetShaderiv", (void *)w_glGetShaderiv },
	{ "glGetShaderPrecisionFormat", (void *)w_glGetShaderPrecisionFormat },
	{ "glGetString", (void *)w_glGetString },
	{ "glGetStringi", (void *)w_glGetStringi },
	{ "glGetTexImage", (void *)w_glGetTexImage },
	{ "glGetTextureImage", (void *)w_glGetTextureImage },
	{ "glGetUniformBlockIndex", (void *)w_glGetUniformBlockIndex },
	{ "glGetUniformLocation", (void *)w_glGetUniformLocation },
	{ "glHint", (void *)w_glHint },
	{ "glInvalidateFramebuffer", (void *)w_glInvalidateFramebuffer },
	{ "glLineWidth", (void *)w_glLineWidth },
	{ "glLinkProgram", (void *)w_glLinkProgram },
	{ "glMapBufferRange", (void *)w_glMapBufferRange },
	{ "glMemoryBarrier", (void *)w_glMemoryBarrier },
	{ "glPixelStorei", (void *)w_glPixelStorei },
	{ "glPolygonMode", (void *)w_glPolygonMode },
	{ "glPrimitiveRestartIndex", (void *)w_glPrimitiveRestartIndex },
	{ "glProgramBinary", (void *)w_glProgramBinary },
	{ "glProgramParameteri", (void *)w_glProgramParameteri },
	{ "glReadBuffer", (void *)w_glReadBuffer },
	{ "glReadPixels", (void *)w_glReadPixels },
	{ "glRenderbufferStorage", (void *)w_glRenderbufferStorage },
	{ "glSamplerParameterf", (void *)w_glSamplerParameterf },
	{ "glSamplerParameteri", (void *)w_glSamplerParameteri },
	{ "glScissor", (void *)w_glScissor },
	{ "glScissorIndexed", (void *)w_glScissorIndexed },
	{ "glShaderSource", (void *)w_glShaderSource },
	{ "glStencilFunc", (void *)w_glStencilFunc },
	{ "glStencilMask", (void *)w_glStencilMask },
	{ "glStencilOp", (void *)w_glStencilOp },
	{ "glTexImage2D", (void *)w_glTexImage2D },
	{ "glTexParameterf", (void *)w_glTexParameterf },
	{ "glTexParameterfv", (void *)w_glTexParameterfv },
	{ "glTexParameteri", (void *)w_glTexParameteri },
	{ "glTexStorage2D", (void *)w_glTexStorage2D },
	{ "glTexSubImage2D", (void *)w_glTexSubImage2D },
	{ "glTextureBarrier", (void *)w_glTextureBarrier },
	{ "glTextureBarrierNV", (void *)w_glTextureBarrierNV },
	{ "glTextureParameteri", (void *)w_glTextureParameteri },
	{ "glTextureStorage2D", (void *)w_glTextureStorage2D },
	{ "glTextureSubImage2D", (void *)w_glTextureSubImage2D },
	{ "glUniform1f", (void *)w_glUniform1f },
	{ "glUniform1i", (void *)w_glUniform1i },
	{ "glUniform1ui", (void *)w_glUniform1ui },
	{ "glUniform2f", (void *)w_glUniform2f },
	{ "glUniform2fv", (void *)w_glUniform2fv },
	{ "glUniform2i", (void *)w_glUniform2i },
	{ "glUniform2iv", (void *)w_glUniform2iv },
	{ "glUniform2ui", (void *)w_glUniform2ui },
	{ "glUniform2uiv", (void *)w_glUniform2uiv },
	{ "glUniform3f", (void *)w_glUniform3f },
	{ "glUniform3fv", (void *)w_glUniform3fv },
	{ "glUniform3i", (void *)w_glUniform3i },
	{ "glUniform3iv", (void *)w_glUniform3iv },
	{ "glUniform3ui", (void *)w_glUniform3ui },
	{ "glUniform3uiv", (void *)w_glUniform3uiv },
	{ "glUniform4f", (void *)w_glUniform4f },
	{ "glUniform4fv", (void *)w_glUniform4fv },
	{ "glUniform4i", (void *)w_glUniform4i },
	{ "glUniform4iv", (void *)w_glUniform4iv },
	{ "glUniform4ui", (void *)w_glUniform4ui },
	{ "glUniform4uiv", (void *)w_glUniform4uiv },
	{ "glUniformBlockBinding", (void *)w_glUniformBlockBinding },
	{ "glUniformMatrix2fv", (void *)w_glUniformMatrix2fv },
	{ "glUniformMatrix3fv", (void *)w_glUniformMatrix3fv },
	{ "glUniformMatrix4fv", (void *)w_glUniformMatrix4fv },
	{ "glUnmapBuffer", (void *)w_glUnmapBuffer },
	{ "glUseProgram", (void *)w_glUseProgram },
	{ "glVertexAttribIPointer", (void *)w_glVertexAttribIPointer },
	{ "glVertexAttribPointer", (void *)w_glVertexAttribPointer },
	{ "glViewport", (void *)w_glViewport },
	{ "glViewportIndexedf", (void *)w_glViewportIndexedf },
	{ "glBlendEquation", (void *)w_glBlendEquation },
	{ "glClearDepth", (void *)w_glClearDepth },
	{ "glDebugMessageInsert", (void *)w_glDebugMessageInsert },
	{ "glFinish", (void *)w_glFinish },
	{ "glFrameTerminatorGREMEDY", (void *)w_glFrameTerminatorGREMEDY },
	{ "glFrontFace", (void *)w_glFrontFace },
	{ "glGetQueryObjectuiv", (void *)w_glGetQueryObjectuiv },
	{ "glMultiDrawArrays", (void *)w_glMultiDrawArrays },
	{ "glObjectLabel", (void *)w_glObjectLabel },
	{ "glPopDebugGroup", (void *)w_glPopDebugGroup },
	{ "glProgramUniform1i", (void *)w_glProgramUniform1i },
	{ "glProgramUniform2f", (void *)w_glProgramUniform2f },
	{ "glProvokingVertex", (void *)w_glProvokingVertex },
	{ "glPushDebugGroup", (void *)w_glPushDebugGroup },
	{ "glTexImage3D", (void *)w_glTexImage3D },
	{ "glTexParameteriv", (void *)w_glTexParameteriv },
	{ "glUniform1fv", (void *)w_glUniform1fv },
	{ "glUniform1iv", (void *)w_glUniform1iv },
	{ "glUniform1uiv", (void *)w_glUniform1uiv },
	{ "glValidateProgram", (void *)w_glValidateProgram },
	{ "glVertexAttrib4fv", (void *)w_glVertexAttrib4fv },
};

/* What a glad loader asks for. Unknown names answer null, which is what glad
 * expects for an entry point the driver does not have. */
void *chimera_gl_lookup(const char *name)
{
	for (size_t i = 0; i < sizeof g_entries / sizeof *g_entries; i++)
	{
		if (std::strcmp(g_entries[i].name, name) == 0)
			return g_entries[i].fn;
	}

	return nullptr;
}
