/* GENERATED by tools/gen-gl-bridge.py from glad's declarations.
 * Do not edit; edit the generator or the name list beside it. */
#pragma once

/* How many entry points the MASTER list holds. A guest built
 * against a longer one than the host has refuses to start. */
#define CHIMERA_GL_OP_LIST_LENGTH 190

/* void glActiveTexture(GLenum texture) */
#define CHIMERA_GL_OP_glActiveTexture 100
struct ChimeraGlArgs_glActiveTexture {
	GLenum texture;
};

/* void glAttachShader(GLuint program, GLuint shader) */
#define CHIMERA_GL_OP_glAttachShader 101
struct ChimeraGlArgs_glAttachShader {
	GLuint program;
	GLuint shader;
};

/* void glBeginQuery(GLenum target, GLuint id) */
#define CHIMERA_GL_OP_glBeginQuery 102
struct ChimeraGlArgs_glBeginQuery {
	GLenum target;
	GLuint id;
};

/* void glBindBuffer(GLenum target, GLuint buffer) */
#define CHIMERA_GL_OP_glBindBuffer 104
struct ChimeraGlArgs_glBindBuffer {
	GLenum target;
	GLuint buffer;
};

/* void glBindFramebuffer(GLenum target, GLuint framebuffer) */
#define CHIMERA_GL_OP_glBindFramebuffer 109
struct ChimeraGlArgs_glBindFramebuffer {
	GLenum target;
	GLuint framebuffer;
};

/* void glBindRenderbuffer(GLenum target, GLuint renderbuffer) */
#define CHIMERA_GL_OP_glBindRenderbuffer 111
struct ChimeraGlArgs_glBindRenderbuffer {
	GLenum target;
	GLuint renderbuffer;
};

/* void glBindTexture(GLenum target, GLuint texture) */
#define CHIMERA_GL_OP_glBindTexture 113
struct ChimeraGlArgs_glBindTexture {
	GLenum target;
	GLuint texture;
};

/* void glBindVertexArray(GLuint array) */
#define CHIMERA_GL_OP_glBindVertexArray 115
struct ChimeraGlArgs_glBindVertexArray {
	GLuint array;
};

/* void glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) */
#define CHIMERA_GL_OP_glBlendColor 116
struct ChimeraGlArgs_glBlendColor {
	GLfloat red;
	GLfloat green;
	GLfloat blue;
	GLfloat alpha;
};

/* void glBlendFunc(GLenum sfactor, GLenum dfactor) */
#define CHIMERA_GL_OP_glBlendFunc 118
struct ChimeraGlArgs_glBlendFunc {
	GLenum sfactor;
	GLenum dfactor;
};

/* void glBufferData(GLenum target, GLsizeiptr size, const void * data, GLenum usage) */
#define CHIMERA_GL_OP_glBufferData 121
struct ChimeraGlArgs_glBufferData {
	GLenum target;
	GLsizeiptr size;
	const void * data;
	GLenum usage;
};

/* void glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void * data) */
#define CHIMERA_GL_OP_glBufferSubData 124
struct ChimeraGlArgs_glBufferSubData {
	GLenum target;
	GLintptr offset;
	GLsizeiptr size;
	const void * data;
};

/* GLenum glCheckFramebufferStatus(GLenum target) */
#define CHIMERA_GL_OP_glCheckFramebufferStatus 125
struct ChimeraGlArgs_glCheckFramebufferStatus {
	GLenum target;
};

/* void glClear(GLbitfield mask) */
#define CHIMERA_GL_OP_glClear 126
struct ChimeraGlArgs_glClear {
	GLbitfield mask;
};

/* void glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) */
#define CHIMERA_GL_OP_glClearColor 130
struct ChimeraGlArgs_glClearColor {
	GLfloat red;
	GLfloat green;
	GLfloat blue;
	GLfloat alpha;
};

/* void glClearStencil(GLint s) */
#define CHIMERA_GL_OP_glClearStencil 132
struct ChimeraGlArgs_glClearStencil {
	GLint s;
};

/* GLenum glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) */
#define CHIMERA_GL_OP_glClientWaitSync 133
struct ChimeraGlArgs_glClientWaitSync {
	GLsync sync;
	GLbitfield flags;
	GLuint64 timeout;
};

/* void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) */
#define CHIMERA_GL_OP_glColorMask 135
struct ChimeraGlArgs_glColorMask {
	GLboolean red;
	GLboolean green;
	GLboolean blue;
	GLboolean alpha;
};

/* void glCompileShader(GLuint shader) */
#define CHIMERA_GL_OP_glCompileShader 137
struct ChimeraGlArgs_glCompileShader {
	GLuint shader;
};

/* GLuint glCreateProgram(void) */
#define CHIMERA_GL_OP_glCreateProgram 145

/* GLuint glCreateShader(GLenum type) */
#define CHIMERA_GL_OP_glCreateShader 147
struct ChimeraGlArgs_glCreateShader {
	GLenum type;
};

/* void glCullFace(GLenum mode) */
#define CHIMERA_GL_OP_glCullFace 149
struct ChimeraGlArgs_glCullFace {
	GLenum mode;
};

/* void glDeleteBuffers(GLsizei n, const GLuint * buffers) */
#define CHIMERA_GL_OP_glDeleteBuffers 152
struct ChimeraGlArgs_glDeleteBuffers {
	GLsizei n;
	const GLuint * buffers;
};

/* void glDeleteFramebuffers(GLsizei n, const GLuint * framebuffers) */
#define CHIMERA_GL_OP_glDeleteFramebuffers 153
struct ChimeraGlArgs_glDeleteFramebuffers {
	GLsizei n;
	const GLuint * framebuffers;
};

/* void glDeleteProgram(GLuint program) */
#define CHIMERA_GL_OP_glDeleteProgram 154
struct ChimeraGlArgs_glDeleteProgram {
	GLuint program;
};

/* void glDeleteQueries(GLsizei n, const GLuint * ids) */
#define CHIMERA_GL_OP_glDeleteQueries 155
struct ChimeraGlArgs_glDeleteQueries {
	GLsizei n;
	const GLuint * ids;
};

/* void glDeleteRenderbuffers(GLsizei n, const GLuint * renderbuffers) */
#define CHIMERA_GL_OP_glDeleteRenderbuffers 156
struct ChimeraGlArgs_glDeleteRenderbuffers {
	GLsizei n;
	const GLuint * renderbuffers;
};

/* void glDeleteShader(GLuint shader) */
#define CHIMERA_GL_OP_glDeleteShader 158
struct ChimeraGlArgs_glDeleteShader {
	GLuint shader;
};

/* void glDeleteSync(GLsync sync) */
#define CHIMERA_GL_OP_glDeleteSync 159
struct ChimeraGlArgs_glDeleteSync {
	GLsync sync;
};

/* void glDeleteTextures(GLsizei n, const GLuint * textures) */
#define CHIMERA_GL_OP_glDeleteTextures 160
struct ChimeraGlArgs_glDeleteTextures {
	GLsizei n;
	const GLuint * textures;
};

/* void glDeleteVertexArrays(GLsizei n, const GLuint * arrays) */
#define CHIMERA_GL_OP_glDeleteVertexArrays 161
struct ChimeraGlArgs_glDeleteVertexArrays {
	GLsizei n;
	const GLuint * arrays;
};

/* void glDepthFunc(GLenum func) */
#define CHIMERA_GL_OP_glDepthFunc 162
struct ChimeraGlArgs_glDepthFunc {
	GLenum func;
};

/* void glDepthMask(GLboolean flag) */
#define CHIMERA_GL_OP_glDepthMask 163
struct ChimeraGlArgs_glDepthMask {
	GLboolean flag;
};

/* void glDisable(GLenum cap) */
#define CHIMERA_GL_OP_glDisable 165
struct ChimeraGlArgs_glDisable {
	GLenum cap;
};

/* void glDisableVertexAttribArray(GLuint index) */
#define CHIMERA_GL_OP_glDisableVertexAttribArray 166
struct ChimeraGlArgs_glDisableVertexAttribArray {
	GLuint index;
};

/* void glDrawArrays(GLenum mode, GLint first, GLsizei count) */
#define CHIMERA_GL_OP_glDrawArrays 168
struct ChimeraGlArgs_glDrawArrays {
	GLenum mode;
	GLint first;
	GLsizei count;
};

/* void glDrawBuffers(GLsizei n, const GLenum * bufs) */
#define CHIMERA_GL_OP_glDrawBuffers 169
struct ChimeraGlArgs_glDrawBuffers {
	GLsizei n;
	const GLenum * bufs;
};

/* void glDrawElements(GLenum mode, GLsizei count, GLenum type, const void * indices) */
#define CHIMERA_GL_OP_glDrawElements 170
struct ChimeraGlArgs_glDrawElements {
	GLenum mode;
	GLsizei count;
	GLenum type;
	const void * indices;
};

/* void glEnable(GLenum cap) */
#define CHIMERA_GL_OP_glEnable 172
struct ChimeraGlArgs_glEnable {
	GLenum cap;
};

/* void glEnableVertexAttribArray(GLuint index) */
#define CHIMERA_GL_OP_glEnableVertexAttribArray 173
struct ChimeraGlArgs_glEnableVertexAttribArray {
	GLuint index;
};

/* void glEndQuery(GLenum target) */
#define CHIMERA_GL_OP_glEndQuery 174
struct ChimeraGlArgs_glEndQuery {
	GLenum target;
};

/* GLsync glFenceSync(GLenum condition, GLbitfield flags) */
#define CHIMERA_GL_OP_glFenceSync 175
struct ChimeraGlArgs_glFenceSync {
	GLenum condition;
	GLbitfield flags;
};

/* void glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) */
#define CHIMERA_GL_OP_glFramebufferRenderbuffer 177
struct ChimeraGlArgs_glFramebufferRenderbuffer {
	GLenum target;
	GLenum attachment;
	GLenum renderbuffertarget;
	GLuint renderbuffer;
};

/* void glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) */
#define CHIMERA_GL_OP_glFramebufferTexture2D 178
struct ChimeraGlArgs_glFramebufferTexture2D {
	GLenum target;
	GLenum attachment;
	GLenum textarget;
	GLuint texture;
	GLint level;
};

/* void glGenBuffers(GLsizei n, GLuint * buffers) */
#define CHIMERA_GL_OP_glGenBuffers 179
struct ChimeraGlArgs_glGenBuffers {
	GLsizei n;
	GLuint * buffers;
};

/* void glGenFramebuffers(GLsizei n, GLuint * framebuffers) */
#define CHIMERA_GL_OP_glGenFramebuffers 182
struct ChimeraGlArgs_glGenFramebuffers {
	GLsizei n;
	GLuint * framebuffers;
};

/* void glGenQueries(GLsizei n, GLuint * ids) */
#define CHIMERA_GL_OP_glGenQueries 183
struct ChimeraGlArgs_glGenQueries {
	GLsizei n;
	GLuint * ids;
};

/* void glGenRenderbuffers(GLsizei n, GLuint * renderbuffers) */
#define CHIMERA_GL_OP_glGenRenderbuffers 184
struct ChimeraGlArgs_glGenRenderbuffers {
	GLsizei n;
	GLuint * renderbuffers;
};

/* void glGenTextures(GLsizei n, GLuint * textures) */
#define CHIMERA_GL_OP_glGenTextures 186
struct ChimeraGlArgs_glGenTextures {
	GLsizei n;
	GLuint * textures;
};

/* void glGenVertexArrays(GLsizei n, GLuint * arrays) */
#define CHIMERA_GL_OP_glGenVertexArrays 187
struct ChimeraGlArgs_glGenVertexArrays {
	GLsizei n;
	GLuint * arrays;
};

/* GLenum glGetError(void) */
#define CHIMERA_GL_OP_glGetError 188

/* void glGetFloatv(GLenum pname, GLfloat * data) */
#define CHIMERA_GL_OP_glGetFloatv 189
struct ChimeraGlArgs_glGetFloatv {
	GLenum pname;
	GLfloat * data;
};

/* void glGetIntegerv(GLenum pname, GLint * data) */
#define CHIMERA_GL_OP_glGetIntegerv 190
struct ChimeraGlArgs_glGetIntegerv {
	GLenum pname;
	GLint * data;
};

/* void glGetProgramBinary(GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, void * binary) */
#define CHIMERA_GL_OP_glGetProgramBinary 191
struct ChimeraGlArgs_glGetProgramBinary {
	GLuint program;
	GLsizei bufSize;
	GLsizei * length;
	GLenum * binaryFormat;
	void * binary;
};

/* void glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog) */
#define CHIMERA_GL_OP_glGetProgramInfoLog 192
struct ChimeraGlArgs_glGetProgramInfoLog {
	GLuint program;
	GLsizei bufSize;
	GLsizei * length;
	GLchar * infoLog;
};

/* void glGetProgramiv(GLuint program, GLenum pname, GLint * params) */
#define CHIMERA_GL_OP_glGetProgramiv 193
struct ChimeraGlArgs_glGetProgramiv {
	GLuint program;
	GLenum pname;
	GLint * params;
};

/* void glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog) */
#define CHIMERA_GL_OP_glGetShaderInfoLog 196
struct ChimeraGlArgs_glGetShaderInfoLog {
	GLuint shader;
	GLsizei bufSize;
	GLsizei * length;
	GLchar * infoLog;
};

/* void glGetShaderiv(GLuint shader, GLenum pname, GLint * params) */
#define CHIMERA_GL_OP_glGetShaderiv 197
struct ChimeraGlArgs_glGetShaderiv {
	GLuint shader;
	GLenum pname;
	GLint * params;
};

/* const GLubyte * glGetString(GLenum name) */
#define CHIMERA_GL_OP_glGetString 199
struct ChimeraGlArgs_glGetString {
	GLenum name;
};

/* const GLubyte * glGetStringi(GLenum name, GLuint index) */
#define CHIMERA_GL_OP_glGetStringi 200
struct ChimeraGlArgs_glGetStringi {
	GLenum name;
	GLuint index;
};

/* GLint glGetUniformLocation(GLuint program, const GLchar * name) */
#define CHIMERA_GL_OP_glGetUniformLocation 204
struct ChimeraGlArgs_glGetUniformLocation {
	GLuint program;
	const GLchar * name;
};

/* void glLineWidth(GLfloat width) */
#define CHIMERA_GL_OP_glLineWidth 207
struct ChimeraGlArgs_glLineWidth {
	GLfloat width;
};

/* void glLinkProgram(GLuint program) */
#define CHIMERA_GL_OP_glLinkProgram 208
struct ChimeraGlArgs_glLinkProgram {
	GLuint program;
};

/* void glPixelStorei(GLenum pname, GLint param) */
#define CHIMERA_GL_OP_glPixelStorei 211
struct ChimeraGlArgs_glPixelStorei {
	GLenum pname;
	GLint param;
};

/* void glPolygonMode(GLenum face, GLenum mode) */
#define CHIMERA_GL_OP_glPolygonMode 212
struct ChimeraGlArgs_glPolygonMode {
	GLenum face;
	GLenum mode;
};

/* void glProgramBinary(GLuint program, GLenum binaryFormat, const void * binary, GLsizei length) */
#define CHIMERA_GL_OP_glProgramBinary 214
struct ChimeraGlArgs_glProgramBinary {
	GLuint program;
	GLenum binaryFormat;
	const void * binary;
	GLsizei length;
};

/* void glReadBuffer(GLenum src) */
#define CHIMERA_GL_OP_glReadBuffer 216
struct ChimeraGlArgs_glReadBuffer {
	GLenum src;
};

/* void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void * pixels) */
#define CHIMERA_GL_OP_glReadPixels 217
struct ChimeraGlArgs_glReadPixels {
	GLint x;
	GLint y;
	GLsizei width;
	GLsizei height;
	GLenum format;
	GLenum type;
	void * pixels;
};

/* void glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) */
#define CHIMERA_GL_OP_glRenderbufferStorage 218
struct ChimeraGlArgs_glRenderbufferStorage {
	GLenum target;
	GLenum internalformat;
	GLsizei width;
	GLsizei height;
};

/* void glScissor(GLint x, GLint y, GLsizei width, GLsizei height) */
#define CHIMERA_GL_OP_glScissor 221
struct ChimeraGlArgs_glScissor {
	GLint x;
	GLint y;
	GLsizei width;
	GLsizei height;
};

/* void glShaderSource(GLuint shader, GLsizei count, const GLchar *const* string, const GLint * length) */
#define CHIMERA_GL_OP_glShaderSource 223
struct ChimeraGlArgs_glShaderSource {
	GLuint shader;
	GLsizei count;
	const GLchar *const* string;
	const GLint * length;
};

/* void glStencilFunc(GLenum func, GLint ref, GLuint mask) */
#define CHIMERA_GL_OP_glStencilFunc 224
struct ChimeraGlArgs_glStencilFunc {
	GLenum func;
	GLint ref;
	GLuint mask;
};

/* void glStencilMask(GLuint mask) */
#define CHIMERA_GL_OP_glStencilMask 225
struct ChimeraGlArgs_glStencilMask {
	GLuint mask;
};

/* void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) */
#define CHIMERA_GL_OP_glStencilOp 226
struct ChimeraGlArgs_glStencilOp {
	GLenum fail;
	GLenum zfail;
	GLenum zpass;
};

/* void glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void * pixels) */
#define CHIMERA_GL_OP_glTexImage2D 227
struct ChimeraGlArgs_glTexImage2D {
	GLenum target;
	GLint level;
	GLint internalformat;
	GLsizei width;
	GLsizei height;
	GLint border;
	GLenum format;
	GLenum type;
	const void * pixels;
};

/* void glTexParameterf(GLenum target, GLenum pname, GLfloat param) */
#define CHIMERA_GL_OP_glTexParameterf 228
struct ChimeraGlArgs_glTexParameterf {
	GLenum target;
	GLenum pname;
	GLfloat param;
};

/* void glTexParameterfv(GLenum target, GLenum pname, const GLfloat * params) */
#define CHIMERA_GL_OP_glTexParameterfv 229
struct ChimeraGlArgs_glTexParameterfv {
	GLenum target;
	GLenum pname;
	const GLfloat * params;
};

/* void glTexParameteri(GLenum target, GLenum pname, GLint param) */
#define CHIMERA_GL_OP_glTexParameteri 230
struct ChimeraGlArgs_glTexParameteri {
	GLenum target;
	GLenum pname;
	GLint param;
};

/* void glUniform1f(GLint location, GLfloat v0) */
#define CHIMERA_GL_OP_glUniform1f 238
struct ChimeraGlArgs_glUniform1f {
	GLint location;
	GLfloat v0;
};

/* void glUniform1i(GLint location, GLint v0) */
#define CHIMERA_GL_OP_glUniform1i 239
struct ChimeraGlArgs_glUniform1i {
	GLint location;
	GLint v0;
};

/* void glUniform1ui(GLint location, GLuint v0) */
#define CHIMERA_GL_OP_glUniform1ui 240
struct ChimeraGlArgs_glUniform1ui {
	GLint location;
	GLuint v0;
};

/* void glUniform2f(GLint location, GLfloat v0, GLfloat v1) */
#define CHIMERA_GL_OP_glUniform2f 241
struct ChimeraGlArgs_glUniform2f {
	GLint location;
	GLfloat v0;
	GLfloat v1;
};

/* void glUniform2fv(GLint location, GLsizei count, const GLfloat * value) */
#define CHIMERA_GL_OP_glUniform2fv 242
struct ChimeraGlArgs_glUniform2fv {
	GLint location;
	GLsizei count;
	const GLfloat * value;
};

/* void glUniform2iv(GLint location, GLsizei count, const GLint * value) */
#define CHIMERA_GL_OP_glUniform2iv 244
struct ChimeraGlArgs_glUniform2iv {
	GLint location;
	GLsizei count;
	const GLint * value;
};

/* void glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) */
#define CHIMERA_GL_OP_glUniform3f 247
struct ChimeraGlArgs_glUniform3f {
	GLint location;
	GLfloat v0;
	GLfloat v1;
	GLfloat v2;
};

/* void glUniform3fv(GLint location, GLsizei count, const GLfloat * value) */
#define CHIMERA_GL_OP_glUniform3fv 248
struct ChimeraGlArgs_glUniform3fv {
	GLint location;
	GLsizei count;
	const GLfloat * value;
};

/* void glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) */
#define CHIMERA_GL_OP_glUniform4f 253
struct ChimeraGlArgs_glUniform4f {
	GLint location;
	GLfloat v0;
	GLfloat v1;
	GLfloat v2;
	GLfloat v3;
};

/* void glUniform4fv(GLint location, GLsizei count, const GLfloat * value) */
#define CHIMERA_GL_OP_glUniform4fv 254
struct ChimeraGlArgs_glUniform4fv {
	GLint location;
	GLsizei count;
	const GLfloat * value;
};

/* void glUniform4iv(GLint location, GLsizei count, const GLint * value) */
#define CHIMERA_GL_OP_glUniform4iv 256
struct ChimeraGlArgs_glUniform4iv {
	GLint location;
	GLsizei count;
	const GLint * value;
};

/* void glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) */
#define CHIMERA_GL_OP_glUniformMatrix2fv 260
struct ChimeraGlArgs_glUniformMatrix2fv {
	GLint location;
	GLsizei count;
	GLboolean transpose;
	const GLfloat * value;
};

/* void glUseProgram(GLuint program) */
#define CHIMERA_GL_OP_glUseProgram 264
struct ChimeraGlArgs_glUseProgram {
	GLuint program;
};

/* void glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void * pointer) */
#define CHIMERA_GL_OP_glVertexAttribIPointer 265
struct ChimeraGlArgs_glVertexAttribIPointer {
	GLuint index;
	GLint size;
	GLenum type;
	GLsizei stride;
	const void * pointer;
};

/* void glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer) */
#define CHIMERA_GL_OP_glVertexAttribPointer 266
struct ChimeraGlArgs_glVertexAttribPointer {
	GLuint index;
	GLint size;
	GLenum type;
	GLboolean normalized;
	GLsizei stride;
	const void * pointer;
};

/* void glViewport(GLint x, GLint y, GLsizei width, GLsizei height) */
#define CHIMERA_GL_OP_glViewport 267
struct ChimeraGlArgs_glViewport {
	GLint x;
	GLint y;
	GLsizei width;
	GLsizei height;
};

/* void glBlendEquation(GLenum mode) */
#define CHIMERA_GL_OP_glBlendEquation 269
struct ChimeraGlArgs_glBlendEquation {
	GLenum mode;
};

/* void glClearDepth(GLdouble depth) */
#define CHIMERA_GL_OP_glClearDepth 270
struct ChimeraGlArgs_glClearDepth {
	GLdouble depth;
};

/* void glDebugMessageInsert(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * buf) */
#define CHIMERA_GL_OP_glDebugMessageInsert 271
struct ChimeraGlArgs_glDebugMessageInsert {
	GLenum source;
	GLenum type;
	GLuint id;
	GLenum severity;
	GLsizei length;
	const GLchar * buf;
};

/* void glFinish(void) */
#define CHIMERA_GL_OP_glFinish 272

/* void glFrameTerminatorGREMEDY(void) */
#define CHIMERA_GL_OP_glFrameTerminatorGREMEDY 273

/* void glFrontFace(GLenum mode) */
#define CHIMERA_GL_OP_glFrontFace 274
struct ChimeraGlArgs_glFrontFace {
	GLenum mode;
};

/* void glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint * params) */
#define CHIMERA_GL_OP_glGetQueryObjectuiv 275
struct ChimeraGlArgs_glGetQueryObjectuiv {
	GLuint id;
	GLenum pname;
	GLuint * params;
};

/* void glMultiDrawArrays(GLenum mode, const GLint * first, const GLsizei * count, GLsizei drawcount) */
#define CHIMERA_GL_OP_glMultiDrawArrays 276
struct ChimeraGlArgs_glMultiDrawArrays {
	GLenum mode;
	const GLint * first;
	const GLsizei * count;
	GLsizei drawcount;
};

/* void glObjectLabel(GLenum identifier, GLuint name, GLsizei length, const GLchar * label) */
#define CHIMERA_GL_OP_glObjectLabel 277
struct ChimeraGlArgs_glObjectLabel {
	GLenum identifier;
	GLuint name;
	GLsizei length;
	const GLchar * label;
};

/* void glPopDebugGroup(void) */
#define CHIMERA_GL_OP_glPopDebugGroup 278

/* void glProgramUniform1i(GLuint program, GLint location, GLint v0) */
#define CHIMERA_GL_OP_glProgramUniform1i 279
struct ChimeraGlArgs_glProgramUniform1i {
	GLuint program;
	GLint location;
	GLint v0;
};

/* void glProgramUniform2f(GLuint program, GLint location, GLfloat v0, GLfloat v1) */
#define CHIMERA_GL_OP_glProgramUniform2f 280
struct ChimeraGlArgs_glProgramUniform2f {
	GLuint program;
	GLint location;
	GLfloat v0;
	GLfloat v1;
};

/* void glProvokingVertex(GLenum mode) */
#define CHIMERA_GL_OP_glProvokingVertex 281
struct ChimeraGlArgs_glProvokingVertex {
	GLenum mode;
};

/* void glPushDebugGroup(GLenum source, GLuint id, GLsizei length, const GLchar * message) */
#define CHIMERA_GL_OP_glPushDebugGroup 282
struct ChimeraGlArgs_glPushDebugGroup {
	GLenum source;
	GLuint id;
	GLsizei length;
	const GLchar * message;
};

/* void glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void * pixels) */
#define CHIMERA_GL_OP_glTexImage3D 283
struct ChimeraGlArgs_glTexImage3D {
	GLenum target;
	GLint level;
	GLint internalformat;
	GLsizei width;
	GLsizei height;
	GLsizei depth;
	GLint border;
	GLenum format;
	GLenum type;
	const void * pixels;
};

/* void glTexParameteriv(GLenum target, GLenum pname, const GLint * params) */
#define CHIMERA_GL_OP_glTexParameteriv 284
struct ChimeraGlArgs_glTexParameteriv {
	GLenum target;
	GLenum pname;
	const GLint * params;
};

/* void glUniform1fv(GLint location, GLsizei count, const GLfloat * value) */
#define CHIMERA_GL_OP_glUniform1fv 285
struct ChimeraGlArgs_glUniform1fv {
	GLint location;
	GLsizei count;
	const GLfloat * value;
};

/* void glUniform1iv(GLint location, GLsizei count, const GLint * value) */
#define CHIMERA_GL_OP_glUniform1iv 286
struct ChimeraGlArgs_glUniform1iv {
	GLint location;
	GLsizei count;
	const GLint * value;
};

/* void glUniform1uiv(GLint location, GLsizei count, const GLuint * value) */
#define CHIMERA_GL_OP_glUniform1uiv 287
struct ChimeraGlArgs_glUniform1uiv {
	GLint location;
	GLsizei count;
	const GLuint * value;
};

/* void glValidateProgram(GLuint program) */
#define CHIMERA_GL_OP_glValidateProgram 288
struct ChimeraGlArgs_glValidateProgram {
	GLuint program;
};

/* void glVertexAttrib4fv(GLuint index, const GLfloat * v) */
#define CHIMERA_GL_OP_glVertexAttrib4fv 289
struct ChimeraGlArgs_glVertexAttrib4fv {
	GLuint index;
	const GLfloat * v;
};

