/* GENERATED by tools/gen-gl-bridge.py from glad's declarations.
 * Do not edit; edit the generator or the name list beside it. */

/* The guest's side: 115 entry points, each one a struct and a call
 * to the sandbox's single callback. Installing them is the whole of what makes
 * this core's renderer talk to a GPU it cannot see. */
#include <glad/gl.h>
#include <cstdint>
#include <cstdio>
#include <cstring>

#include "gl-bridge.h"
#include "gl-bridge-ops.h"

static chimera_gl_bridge_fn g_bridge;

static void GLAD_API_PTR w_glActiveTexture(GLenum texture)
{
	struct ChimeraGlArgs_glActiveTexture chimera_a;
	chimera_a.texture = texture;
	g_bridge(CHIMERA_GL_OP_glActiveTexture, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glAttachShader(GLuint program, GLuint shader)
{
	struct ChimeraGlArgs_glAttachShader chimera_a;
	chimera_a.program = program;
	chimera_a.shader = shader;
	g_bridge(CHIMERA_GL_OP_glAttachShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBeginQuery(GLenum target, GLuint id)
{
	struct ChimeraGlArgs_glBeginQuery chimera_a;
	chimera_a.target = target;
	chimera_a.id = id;
	g_bridge(CHIMERA_GL_OP_glBeginQuery, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindBuffer(GLenum target, GLuint buffer)
{
	struct ChimeraGlArgs_glBindBuffer chimera_a;
	chimera_a.target = target;
	chimera_a.buffer = buffer;
	g_bridge(CHIMERA_GL_OP_glBindBuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindFramebuffer(GLenum target, GLuint framebuffer)
{
	struct ChimeraGlArgs_glBindFramebuffer chimera_a;
	chimera_a.target = target;
	chimera_a.framebuffer = framebuffer;
	g_bridge(CHIMERA_GL_OP_glBindFramebuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindRenderbuffer(GLenum target, GLuint renderbuffer)
{
	struct ChimeraGlArgs_glBindRenderbuffer chimera_a;
	chimera_a.target = target;
	chimera_a.renderbuffer = renderbuffer;
	g_bridge(CHIMERA_GL_OP_glBindRenderbuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindTexture(GLenum target, GLuint texture)
{
	struct ChimeraGlArgs_glBindTexture chimera_a;
	chimera_a.target = target;
	chimera_a.texture = texture;
	g_bridge(CHIMERA_GL_OP_glBindTexture, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBindVertexArray(GLuint array)
{
	struct ChimeraGlArgs_glBindVertexArray chimera_a;
	chimera_a.array = array;
	g_bridge(CHIMERA_GL_OP_glBindVertexArray, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
	struct ChimeraGlArgs_glBlendColor chimera_a;
	chimera_a.red = red;
	chimera_a.green = green;
	chimera_a.blue = blue;
	chimera_a.alpha = alpha;
	g_bridge(CHIMERA_GL_OP_glBlendColor, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendFunc(GLenum sfactor, GLenum dfactor)
{
	struct ChimeraGlArgs_glBlendFunc chimera_a;
	chimera_a.sfactor = sfactor;
	chimera_a.dfactor = dfactor;
	g_bridge(CHIMERA_GL_OP_glBlendFunc, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBufferData(GLenum target, GLsizeiptr size, const void * data, GLenum usage)
{
	struct ChimeraGlArgs_glBufferData chimera_a;
	chimera_a.target = target;
	chimera_a.size = size;
	chimera_a.data = data;
	chimera_a.usage = usage;
	g_bridge(CHIMERA_GL_OP_glBufferData, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void * data)
{
	struct ChimeraGlArgs_glBufferSubData chimera_a;
	chimera_a.target = target;
	chimera_a.offset = offset;
	chimera_a.size = size;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glBufferSubData, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLenum GLAD_API_PTR w_glCheckFramebufferStatus(GLenum target)
{
	struct ChimeraGlArgs_glCheckFramebufferStatus chimera_a;
	chimera_a.target = target;
	return (GLenum)g_bridge(CHIMERA_GL_OP_glCheckFramebufferStatus, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClear(GLbitfield mask)
{
	struct ChimeraGlArgs_glClear chimera_a;
	chimera_a.mask = mask;
	g_bridge(CHIMERA_GL_OP_glClear, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
	struct ChimeraGlArgs_glClearColor chimera_a;
	chimera_a.red = red;
	chimera_a.green = green;
	chimera_a.blue = blue;
	chimera_a.alpha = alpha;
	g_bridge(CHIMERA_GL_OP_glClearColor, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearStencil(GLint s)
{
	struct ChimeraGlArgs_glClearStencil chimera_a;
	chimera_a.s = s;
	g_bridge(CHIMERA_GL_OP_glClearStencil, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLenum GLAD_API_PTR w_glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout)
{
	struct ChimeraGlArgs_glClientWaitSync chimera_a;
	chimera_a.sync = sync;
	chimera_a.flags = flags;
	chimera_a.timeout = timeout;
	return (GLenum)g_bridge(CHIMERA_GL_OP_glClientWaitSync, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
	struct ChimeraGlArgs_glColorMask chimera_a;
	chimera_a.red = red;
	chimera_a.green = green;
	chimera_a.blue = blue;
	chimera_a.alpha = alpha;
	g_bridge(CHIMERA_GL_OP_glColorMask, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCompileShader(GLuint shader)
{
	struct ChimeraGlArgs_glCompileShader chimera_a;
	chimera_a.shader = shader;
	g_bridge(CHIMERA_GL_OP_glCompileShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLuint GLAD_API_PTR w_glCreateProgram(void)
{
	return (GLuint)g_bridge(CHIMERA_GL_OP_glCreateProgram, 0, 0, 0, 0, 0);
}

static GLuint GLAD_API_PTR w_glCreateShader(GLenum type)
{
	struct ChimeraGlArgs_glCreateShader chimera_a;
	chimera_a.type = type;
	return (GLuint)g_bridge(CHIMERA_GL_OP_glCreateShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glCullFace(GLenum mode)
{
	struct ChimeraGlArgs_glCullFace chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glCullFace, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteBuffers(GLsizei n, const GLuint * buffers)
{
	struct ChimeraGlArgs_glDeleteBuffers chimera_a;
	chimera_a.n = n;
	chimera_a.buffers = buffers;
	g_bridge(CHIMERA_GL_OP_glDeleteBuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteFramebuffers(GLsizei n, const GLuint * framebuffers)
{
	struct ChimeraGlArgs_glDeleteFramebuffers chimera_a;
	chimera_a.n = n;
	chimera_a.framebuffers = framebuffers;
	g_bridge(CHIMERA_GL_OP_glDeleteFramebuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteProgram(GLuint program)
{
	struct ChimeraGlArgs_glDeleteProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glDeleteProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteQueries(GLsizei n, const GLuint * ids)
{
	struct ChimeraGlArgs_glDeleteQueries chimera_a;
	chimera_a.n = n;
	chimera_a.ids = ids;
	g_bridge(CHIMERA_GL_OP_glDeleteQueries, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteRenderbuffers(GLsizei n, const GLuint * renderbuffers)
{
	struct ChimeraGlArgs_glDeleteRenderbuffers chimera_a;
	chimera_a.n = n;
	chimera_a.renderbuffers = renderbuffers;
	g_bridge(CHIMERA_GL_OP_glDeleteRenderbuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteShader(GLuint shader)
{
	struct ChimeraGlArgs_glDeleteShader chimera_a;
	chimera_a.shader = shader;
	g_bridge(CHIMERA_GL_OP_glDeleteShader, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteSync(GLsync sync)
{
	struct ChimeraGlArgs_glDeleteSync chimera_a;
	chimera_a.sync = sync;
	g_bridge(CHIMERA_GL_OP_glDeleteSync, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteTextures(GLsizei n, const GLuint * textures)
{
	struct ChimeraGlArgs_glDeleteTextures chimera_a;
	chimera_a.n = n;
	chimera_a.textures = textures;
	g_bridge(CHIMERA_GL_OP_glDeleteTextures, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDeleteVertexArrays(GLsizei n, const GLuint * arrays)
{
	struct ChimeraGlArgs_glDeleteVertexArrays chimera_a;
	chimera_a.n = n;
	chimera_a.arrays = arrays;
	g_bridge(CHIMERA_GL_OP_glDeleteVertexArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDepthFunc(GLenum func)
{
	struct ChimeraGlArgs_glDepthFunc chimera_a;
	chimera_a.func = func;
	g_bridge(CHIMERA_GL_OP_glDepthFunc, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDepthMask(GLboolean flag)
{
	struct ChimeraGlArgs_glDepthMask chimera_a;
	chimera_a.flag = flag;
	g_bridge(CHIMERA_GL_OP_glDepthMask, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDisable(GLenum cap)
{
	struct ChimeraGlArgs_glDisable chimera_a;
	chimera_a.cap = cap;
	g_bridge(CHIMERA_GL_OP_glDisable, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDisableVertexAttribArray(GLuint index)
{
	struct ChimeraGlArgs_glDisableVertexAttribArray chimera_a;
	chimera_a.index = index;
	g_bridge(CHIMERA_GL_OP_glDisableVertexAttribArray, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
	struct ChimeraGlArgs_glDrawArrays chimera_a;
	chimera_a.mode = mode;
	chimera_a.first = first;
	chimera_a.count = count;
	g_bridge(CHIMERA_GL_OP_glDrawArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDrawBuffers(GLsizei n, const GLenum * bufs)
{
	struct ChimeraGlArgs_glDrawBuffers chimera_a;
	chimera_a.n = n;
	chimera_a.bufs = bufs;
	g_bridge(CHIMERA_GL_OP_glDrawBuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDrawElements(GLenum mode, GLsizei count, GLenum type, const void * indices)
{
	struct ChimeraGlArgs_glDrawElements chimera_a;
	chimera_a.mode = mode;
	chimera_a.count = count;
	chimera_a.type = type;
	chimera_a.indices = indices;
	g_bridge(CHIMERA_GL_OP_glDrawElements, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glEnable(GLenum cap)
{
	struct ChimeraGlArgs_glEnable chimera_a;
	chimera_a.cap = cap;
	g_bridge(CHIMERA_GL_OP_glEnable, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glEnableVertexAttribArray(GLuint index)
{
	struct ChimeraGlArgs_glEnableVertexAttribArray chimera_a;
	chimera_a.index = index;
	g_bridge(CHIMERA_GL_OP_glEnableVertexAttribArray, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glEndQuery(GLenum target)
{
	struct ChimeraGlArgs_glEndQuery chimera_a;
	chimera_a.target = target;
	g_bridge(CHIMERA_GL_OP_glEndQuery, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLsync GLAD_API_PTR w_glFenceSync(GLenum condition, GLbitfield flags)
{
	struct ChimeraGlArgs_glFenceSync chimera_a;
	chimera_a.condition = condition;
	chimera_a.flags = flags;
	return (GLsync)g_bridge(CHIMERA_GL_OP_glFenceSync, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
{
	struct ChimeraGlArgs_glFramebufferRenderbuffer chimera_a;
	chimera_a.target = target;
	chimera_a.attachment = attachment;
	chimera_a.renderbuffertarget = renderbuffertarget;
	chimera_a.renderbuffer = renderbuffer;
	g_bridge(CHIMERA_GL_OP_glFramebufferRenderbuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
{
	struct ChimeraGlArgs_glFramebufferTexture2D chimera_a;
	chimera_a.target = target;
	chimera_a.attachment = attachment;
	chimera_a.textarget = textarget;
	chimera_a.texture = texture;
	chimera_a.level = level;
	g_bridge(CHIMERA_GL_OP_glFramebufferTexture2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenBuffers(GLsizei n, GLuint * buffers)
{
	struct ChimeraGlArgs_glGenBuffers chimera_a;
	chimera_a.n = n;
	chimera_a.buffers = buffers;
	g_bridge(CHIMERA_GL_OP_glGenBuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenFramebuffers(GLsizei n, GLuint * framebuffers)
{
	struct ChimeraGlArgs_glGenFramebuffers chimera_a;
	chimera_a.n = n;
	chimera_a.framebuffers = framebuffers;
	g_bridge(CHIMERA_GL_OP_glGenFramebuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenQueries(GLsizei n, GLuint * ids)
{
	struct ChimeraGlArgs_glGenQueries chimera_a;
	chimera_a.n = n;
	chimera_a.ids = ids;
	g_bridge(CHIMERA_GL_OP_glGenQueries, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenRenderbuffers(GLsizei n, GLuint * renderbuffers)
{
	struct ChimeraGlArgs_glGenRenderbuffers chimera_a;
	chimera_a.n = n;
	chimera_a.renderbuffers = renderbuffers;
	g_bridge(CHIMERA_GL_OP_glGenRenderbuffers, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenTextures(GLsizei n, GLuint * textures)
{
	struct ChimeraGlArgs_glGenTextures chimera_a;
	chimera_a.n = n;
	chimera_a.textures = textures;
	g_bridge(CHIMERA_GL_OP_glGenTextures, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGenVertexArrays(GLsizei n, GLuint * arrays)
{
	struct ChimeraGlArgs_glGenVertexArrays chimera_a;
	chimera_a.n = n;
	chimera_a.arrays = arrays;
	g_bridge(CHIMERA_GL_OP_glGenVertexArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static GLenum GLAD_API_PTR w_glGetError(void)
{
	return (GLenum)g_bridge(CHIMERA_GL_OP_glGetError, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetFloatv(GLenum pname, GLfloat * data)
{
	struct ChimeraGlArgs_glGetFloatv chimera_a;
	chimera_a.pname = pname;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glGetFloatv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetIntegerv(GLenum pname, GLint * data)
{
	struct ChimeraGlArgs_glGetIntegerv chimera_a;
	chimera_a.pname = pname;
	chimera_a.data = data;
	g_bridge(CHIMERA_GL_OP_glGetIntegerv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetProgramBinary(GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, void * binary)
{
	struct ChimeraGlArgs_glGetProgramBinary chimera_a;
	chimera_a.program = program;
	chimera_a.bufSize = bufSize;
	chimera_a.length = length;
	chimera_a.binaryFormat = binaryFormat;
	chimera_a.binary = binary;
	g_bridge(CHIMERA_GL_OP_glGetProgramBinary, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
{
	struct ChimeraGlArgs_glGetProgramInfoLog chimera_a;
	chimera_a.program = program;
	chimera_a.bufSize = bufSize;
	chimera_a.length = length;
	chimera_a.infoLog = infoLog;
	g_bridge(CHIMERA_GL_OP_glGetProgramInfoLog, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetProgramiv(GLuint program, GLenum pname, GLint * params)
{
	struct ChimeraGlArgs_glGetProgramiv chimera_a;
	chimera_a.program = program;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetProgramiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
{
	struct ChimeraGlArgs_glGetShaderInfoLog chimera_a;
	chimera_a.shader = shader;
	chimera_a.bufSize = bufSize;
	chimera_a.length = length;
	chimera_a.infoLog = infoLog;
	g_bridge(CHIMERA_GL_OP_glGetShaderInfoLog, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetShaderiv(GLuint shader, GLenum pname, GLint * params)
{
	struct ChimeraGlArgs_glGetShaderiv chimera_a;
	chimera_a.shader = shader;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetShaderiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static const GLubyte *GLAD_API_PTR w_glGetString(GLenum name)
{
	static char buffer[4096];
	struct ChimeraGlArgs_glGetString chimera_a;
	chimera_a.name = name;
	g_bridge(CHIMERA_GL_OP_glGetString, (uint64_t)(uintptr_t)&chimera_a,
		(uint64_t)(uintptr_t)buffer, sizeof buffer, 0, 0);
	return buffer[0] ? (const GLubyte *)buffer : NULL;
}

static const GLubyte *GLAD_API_PTR w_glGetStringi(GLenum name, GLuint index)
{
	static char buffer[4096];
	struct ChimeraGlArgs_glGetStringi chimera_a;
	chimera_a.name = name;
	chimera_a.index = index;
	g_bridge(CHIMERA_GL_OP_glGetStringi, (uint64_t)(uintptr_t)&chimera_a,
		(uint64_t)(uintptr_t)buffer, sizeof buffer, 0, 0);
	return buffer[0] ? (const GLubyte *)buffer : NULL;
}

static GLint GLAD_API_PTR w_glGetUniformLocation(GLuint program, const GLchar * name)
{
	struct ChimeraGlArgs_glGetUniformLocation chimera_a;
	chimera_a.program = program;
	chimera_a.name = name;
	return (GLint)g_bridge(CHIMERA_GL_OP_glGetUniformLocation, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glLineWidth(GLfloat width)
{
	struct ChimeraGlArgs_glLineWidth chimera_a;
	chimera_a.width = width;
	g_bridge(CHIMERA_GL_OP_glLineWidth, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glLinkProgram(GLuint program)
{
	struct ChimeraGlArgs_glLinkProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glLinkProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPixelStorei(GLenum pname, GLint param)
{
	struct ChimeraGlArgs_glPixelStorei chimera_a;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glPixelStorei, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPolygonMode(GLenum face, GLenum mode)
{
	struct ChimeraGlArgs_glPolygonMode chimera_a;
	chimera_a.face = face;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glPolygonMode, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProgramBinary(GLuint program, GLenum binaryFormat, const void * binary, GLsizei length)
{
	struct ChimeraGlArgs_glProgramBinary chimera_a;
	chimera_a.program = program;
	chimera_a.binaryFormat = binaryFormat;
	chimera_a.binary = binary;
	chimera_a.length = length;
	g_bridge(CHIMERA_GL_OP_glProgramBinary, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glReadBuffer(GLenum src)
{
	struct ChimeraGlArgs_glReadBuffer chimera_a;
	chimera_a.src = src;
	g_bridge(CHIMERA_GL_OP_glReadBuffer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void * pixels)
{
	struct ChimeraGlArgs_glReadPixels chimera_a;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glReadPixels, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glRenderbufferStorage chimera_a;
	chimera_a.target = target;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glRenderbufferStorage, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glScissor chimera_a;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glScissor, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glShaderSource(GLuint shader, GLsizei count, const GLchar *const* string, const GLint * length)
{
	struct ChimeraGlArgs_glShaderSource chimera_a;
	chimera_a.shader = shader;
	chimera_a.count = count;
	chimera_a.string = string;
	chimera_a.length = length;
	g_bridge(CHIMERA_GL_OP_glShaderSource, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
	struct ChimeraGlArgs_glStencilFunc chimera_a;
	chimera_a.func = func;
	chimera_a.ref = ref;
	chimera_a.mask = mask;
	g_bridge(CHIMERA_GL_OP_glStencilFunc, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glStencilMask(GLuint mask)
{
	struct ChimeraGlArgs_glStencilMask chimera_a;
	chimera_a.mask = mask;
	g_bridge(CHIMERA_GL_OP_glStencilMask, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
	struct ChimeraGlArgs_glStencilOp chimera_a;
	chimera_a.fail = fail;
	chimera_a.zfail = zfail;
	chimera_a.zpass = zpass;
	g_bridge(CHIMERA_GL_OP_glStencilOp, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void * pixels)
{
	struct ChimeraGlArgs_glTexImage2D chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.border = border;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glTexImage2D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
	struct ChimeraGlArgs_glTexParameterf chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glTexParameterf, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameterfv(GLenum target, GLenum pname, const GLfloat * params)
{
	struct ChimeraGlArgs_glTexParameterfv chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glTexParameterfv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameteri(GLenum target, GLenum pname, GLint param)
{
	struct ChimeraGlArgs_glTexParameteri chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.param = param;
	g_bridge(CHIMERA_GL_OP_glTexParameteri, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1f(GLint location, GLfloat v0)
{
	struct ChimeraGlArgs_glUniform1f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glUniform1f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1i(GLint location, GLint v0)
{
	struct ChimeraGlArgs_glUniform1i chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glUniform1i, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1ui(GLint location, GLuint v0)
{
	struct ChimeraGlArgs_glUniform1ui chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glUniform1ui, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2f(GLint location, GLfloat v0, GLfloat v1)
{
	struct ChimeraGlArgs_glUniform2f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	g_bridge(CHIMERA_GL_OP_glUniform2f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform2fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform2fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform2iv(GLint location, GLsizei count, const GLint * value)
{
	struct ChimeraGlArgs_glUniform2iv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform2iv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
{
	struct ChimeraGlArgs_glUniform3f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	g_bridge(CHIMERA_GL_OP_glUniform3f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform3fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform3fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform3fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
{
	struct ChimeraGlArgs_glUniform4f chimera_a;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	chimera_a.v2 = v2;
	chimera_a.v3 = v3;
	g_bridge(CHIMERA_GL_OP_glUniform4f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform4fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform4fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform4iv(GLint location, GLsizei count, const GLint * value)
{
	struct ChimeraGlArgs_glUniform4iv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform4iv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniformMatrix2fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.transpose = transpose;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniformMatrix2fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUseProgram(GLuint program)
{
	struct ChimeraGlArgs_glUseProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glUseProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void * pointer)
{
	struct ChimeraGlArgs_glVertexAttribIPointer chimera_a;
	chimera_a.index = index;
	chimera_a.size = size;
	chimera_a.type = type;
	chimera_a.stride = stride;
	chimera_a.pointer = pointer;
	g_bridge(CHIMERA_GL_OP_glVertexAttribIPointer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer)
{
	struct ChimeraGlArgs_glVertexAttribPointer chimera_a;
	chimera_a.index = index;
	chimera_a.size = size;
	chimera_a.type = type;
	chimera_a.normalized = normalized;
	chimera_a.stride = stride;
	chimera_a.pointer = pointer;
	g_bridge(CHIMERA_GL_OP_glVertexAttribPointer, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
	struct ChimeraGlArgs_glViewport chimera_a;
	chimera_a.x = x;
	chimera_a.y = y;
	chimera_a.width = width;
	chimera_a.height = height;
	g_bridge(CHIMERA_GL_OP_glViewport, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glBlendEquation(GLenum mode)
{
	struct ChimeraGlArgs_glBlendEquation chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glBlendEquation, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glClearDepth(GLdouble depth)
{
	struct ChimeraGlArgs_glClearDepth chimera_a;
	chimera_a.depth = depth;
	g_bridge(CHIMERA_GL_OP_glClearDepth, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glDebugMessageInsert(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * buf)
{
	struct ChimeraGlArgs_glDebugMessageInsert chimera_a;
	chimera_a.source = source;
	chimera_a.type = type;
	chimera_a.id = id;
	chimera_a.severity = severity;
	chimera_a.length = length;
	chimera_a.buf = buf;
	g_bridge(CHIMERA_GL_OP_glDebugMessageInsert, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFinish(void)
{
	g_bridge(CHIMERA_GL_OP_glFinish, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFrameTerminatorGREMEDY(void)
{
	g_bridge(CHIMERA_GL_OP_glFrameTerminatorGREMEDY, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glFrontFace(GLenum mode)
{
	struct ChimeraGlArgs_glFrontFace chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glFrontFace, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint * params)
{
	struct ChimeraGlArgs_glGetQueryObjectuiv chimera_a;
	chimera_a.id = id;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glGetQueryObjectuiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glMultiDrawArrays(GLenum mode, const GLint * first, const GLsizei * count, GLsizei drawcount)
{
	struct ChimeraGlArgs_glMultiDrawArrays chimera_a;
	chimera_a.mode = mode;
	chimera_a.first = first;
	chimera_a.count = count;
	chimera_a.drawcount = drawcount;
	g_bridge(CHIMERA_GL_OP_glMultiDrawArrays, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glObjectLabel(GLenum identifier, GLuint name, GLsizei length, const GLchar * label)
{
	struct ChimeraGlArgs_glObjectLabel chimera_a;
	chimera_a.identifier = identifier;
	chimera_a.name = name;
	chimera_a.length = length;
	chimera_a.label = label;
	g_bridge(CHIMERA_GL_OP_glObjectLabel, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPopDebugGroup(void)
{
	g_bridge(CHIMERA_GL_OP_glPopDebugGroup, 0, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProgramUniform1i(GLuint program, GLint location, GLint v0)
{
	struct ChimeraGlArgs_glProgramUniform1i chimera_a;
	chimera_a.program = program;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	g_bridge(CHIMERA_GL_OP_glProgramUniform1i, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProgramUniform2f(GLuint program, GLint location, GLfloat v0, GLfloat v1)
{
	struct ChimeraGlArgs_glProgramUniform2f chimera_a;
	chimera_a.program = program;
	chimera_a.location = location;
	chimera_a.v0 = v0;
	chimera_a.v1 = v1;
	g_bridge(CHIMERA_GL_OP_glProgramUniform2f, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glProvokingVertex(GLenum mode)
{
	struct ChimeraGlArgs_glProvokingVertex chimera_a;
	chimera_a.mode = mode;
	g_bridge(CHIMERA_GL_OP_glProvokingVertex, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glPushDebugGroup(GLenum source, GLuint id, GLsizei length, const GLchar * message)
{
	struct ChimeraGlArgs_glPushDebugGroup chimera_a;
	chimera_a.source = source;
	chimera_a.id = id;
	chimera_a.length = length;
	chimera_a.message = message;
	g_bridge(CHIMERA_GL_OP_glPushDebugGroup, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void * pixels)
{
	struct ChimeraGlArgs_glTexImage3D chimera_a;
	chimera_a.target = target;
	chimera_a.level = level;
	chimera_a.internalformat = internalformat;
	chimera_a.width = width;
	chimera_a.height = height;
	chimera_a.depth = depth;
	chimera_a.border = border;
	chimera_a.format = format;
	chimera_a.type = type;
	chimera_a.pixels = pixels;
	g_bridge(CHIMERA_GL_OP_glTexImage3D, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glTexParameteriv(GLenum target, GLenum pname, const GLint * params)
{
	struct ChimeraGlArgs_glTexParameteriv chimera_a;
	chimera_a.target = target;
	chimera_a.pname = pname;
	chimera_a.params = params;
	g_bridge(CHIMERA_GL_OP_glTexParameteriv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1fv(GLint location, GLsizei count, const GLfloat * value)
{
	struct ChimeraGlArgs_glUniform1fv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform1fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1iv(GLint location, GLsizei count, const GLint * value)
{
	struct ChimeraGlArgs_glUniform1iv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform1iv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glUniform1uiv(GLint location, GLsizei count, const GLuint * value)
{
	struct ChimeraGlArgs_glUniform1uiv chimera_a;
	chimera_a.location = location;
	chimera_a.count = count;
	chimera_a.value = value;
	g_bridge(CHIMERA_GL_OP_glUniform1uiv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glValidateProgram(GLuint program)
{
	struct ChimeraGlArgs_glValidateProgram chimera_a;
	chimera_a.program = program;
	g_bridge(CHIMERA_GL_OP_glValidateProgram, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

static void GLAD_API_PTR w_glVertexAttrib4fv(GLuint index, const GLfloat * v)
{
	struct ChimeraGlArgs_glVertexAttrib4fv chimera_a;
	chimera_a.index = index;
	chimera_a.v = v;
	g_bridge(CHIMERA_GL_OP_glVertexAttrib4fv, (uint64_t)(uintptr_t)&chimera_a, 0, 0, 0, 0);
}

/* Returns false when the host is older than this guest - it would not know
 * every opcode this guest can emit, and the core must draw some other way. */
bool chimera_gl_install(chimera_gl_bridge_fn bridge)
{
	uint64_t host_length = bridge(GL_OP_LIST_LENGTH, 0, 0, 0, 0, 0);
	if (host_length < CHIMERA_GL_OP_LIST_LENGTH)
	{
		fprintf(stderr, "chimera gl: the host knows %llu entry points and this "
			"core was built against %d; not bridging\n",
			(unsigned long long)host_length, CHIMERA_GL_OP_LIST_LENGTH);
		return false;
	}

	g_bridge = bridge;
	glad_glActiveTexture = w_glActiveTexture;
	glad_glAttachShader = w_glAttachShader;
	glad_glBeginQuery = w_glBeginQuery;
	glad_glBindBuffer = w_glBindBuffer;
	glad_glBindFramebuffer = w_glBindFramebuffer;
	glad_glBindRenderbuffer = w_glBindRenderbuffer;
	glad_glBindTexture = w_glBindTexture;
	glad_glBindVertexArray = w_glBindVertexArray;
	glad_glBlendColor = w_glBlendColor;
	glad_glBlendFunc = w_glBlendFunc;
	glad_glBufferData = w_glBufferData;
	glad_glBufferSubData = w_glBufferSubData;
	glad_glCheckFramebufferStatus = w_glCheckFramebufferStatus;
	glad_glClear = w_glClear;
	glad_glClearColor = w_glClearColor;
	glad_glClearStencil = w_glClearStencil;
	glad_glClientWaitSync = w_glClientWaitSync;
	glad_glColorMask = w_glColorMask;
	glad_glCompileShader = w_glCompileShader;
	glad_glCreateProgram = w_glCreateProgram;
	glad_glCreateShader = w_glCreateShader;
	glad_glCullFace = w_glCullFace;
	glad_glDeleteBuffers = w_glDeleteBuffers;
	glad_glDeleteFramebuffers = w_glDeleteFramebuffers;
	glad_glDeleteProgram = w_glDeleteProgram;
	glad_glDeleteQueries = w_glDeleteQueries;
	glad_glDeleteRenderbuffers = w_glDeleteRenderbuffers;
	glad_glDeleteShader = w_glDeleteShader;
	glad_glDeleteSync = w_glDeleteSync;
	glad_glDeleteTextures = w_glDeleteTextures;
	glad_glDeleteVertexArrays = w_glDeleteVertexArrays;
	glad_glDepthFunc = w_glDepthFunc;
	glad_glDepthMask = w_glDepthMask;
	glad_glDisable = w_glDisable;
	glad_glDisableVertexAttribArray = w_glDisableVertexAttribArray;
	glad_glDrawArrays = w_glDrawArrays;
	glad_glDrawBuffers = w_glDrawBuffers;
	glad_glDrawElements = w_glDrawElements;
	glad_glEnable = w_glEnable;
	glad_glEnableVertexAttribArray = w_glEnableVertexAttribArray;
	glad_glEndQuery = w_glEndQuery;
	glad_glFenceSync = w_glFenceSync;
	glad_glFramebufferRenderbuffer = w_glFramebufferRenderbuffer;
	glad_glFramebufferTexture2D = w_glFramebufferTexture2D;
	glad_glGenBuffers = w_glGenBuffers;
	glad_glGenFramebuffers = w_glGenFramebuffers;
	glad_glGenQueries = w_glGenQueries;
	glad_glGenRenderbuffers = w_glGenRenderbuffers;
	glad_glGenTextures = w_glGenTextures;
	glad_glGenVertexArrays = w_glGenVertexArrays;
	glad_glGetError = w_glGetError;
	glad_glGetFloatv = w_glGetFloatv;
	glad_glGetIntegerv = w_glGetIntegerv;
	glad_glGetProgramBinary = w_glGetProgramBinary;
	glad_glGetProgramInfoLog = w_glGetProgramInfoLog;
	glad_glGetProgramiv = w_glGetProgramiv;
	glad_glGetShaderInfoLog = w_glGetShaderInfoLog;
	glad_glGetShaderiv = w_glGetShaderiv;
	glad_glGetString = w_glGetString;
	glad_glGetStringi = w_glGetStringi;
	glad_glGetUniformLocation = w_glGetUniformLocation;
	glad_glLineWidth = w_glLineWidth;
	glad_glLinkProgram = w_glLinkProgram;
	glad_glPixelStorei = w_glPixelStorei;
	glad_glPolygonMode = w_glPolygonMode;
	glad_glProgramBinary = w_glProgramBinary;
	glad_glReadBuffer = w_glReadBuffer;
	glad_glReadPixels = w_glReadPixels;
	glad_glRenderbufferStorage = w_glRenderbufferStorage;
	glad_glScissor = w_glScissor;
	glad_glShaderSource = w_glShaderSource;
	glad_glStencilFunc = w_glStencilFunc;
	glad_glStencilMask = w_glStencilMask;
	glad_glStencilOp = w_glStencilOp;
	glad_glTexImage2D = w_glTexImage2D;
	glad_glTexParameterf = w_glTexParameterf;
	glad_glTexParameterfv = w_glTexParameterfv;
	glad_glTexParameteri = w_glTexParameteri;
	glad_glUniform1f = w_glUniform1f;
	glad_glUniform1i = w_glUniform1i;
	glad_glUniform1ui = w_glUniform1ui;
	glad_glUniform2f = w_glUniform2f;
	glad_glUniform2fv = w_glUniform2fv;
	glad_glUniform2iv = w_glUniform2iv;
	glad_glUniform3f = w_glUniform3f;
	glad_glUniform3fv = w_glUniform3fv;
	glad_glUniform4f = w_glUniform4f;
	glad_glUniform4fv = w_glUniform4fv;
	glad_glUniform4iv = w_glUniform4iv;
	glad_glUniformMatrix2fv = w_glUniformMatrix2fv;
	glad_glUseProgram = w_glUseProgram;
	glad_glVertexAttribIPointer = w_glVertexAttribIPointer;
	glad_glVertexAttribPointer = w_glVertexAttribPointer;
	glad_glViewport = w_glViewport;
	glad_glBlendEquation = w_glBlendEquation;
	glad_glClearDepth = w_glClearDepth;
	glad_glDebugMessageInsert = w_glDebugMessageInsert;
	glad_glFinish = w_glFinish;
	glad_glFrameTerminatorGREMEDY = w_glFrameTerminatorGREMEDY;
	glad_glFrontFace = w_glFrontFace;
	glad_glGetQueryObjectuiv = w_glGetQueryObjectuiv;
	glad_glMultiDrawArrays = w_glMultiDrawArrays;
	glad_glObjectLabel = w_glObjectLabel;
	glad_glPopDebugGroup = w_glPopDebugGroup;
	glad_glProgramUniform1i = w_glProgramUniform1i;
	glad_glProgramUniform2f = w_glProgramUniform2f;
	glad_glProvokingVertex = w_glProvokingVertex;
	glad_glPushDebugGroup = w_glPushDebugGroup;
	glad_glTexImage3D = w_glTexImage3D;
	glad_glTexParameteriv = w_glTexParameteriv;
	glad_glUniform1fv = w_glUniform1fv;
	glad_glUniform1iv = w_glUniform1iv;
	glad_glUniform1uiv = w_glUniform1uiv;
	glad_glValidateProgram = w_glValidateProgram;
	glad_glVertexAttrib4fv = w_glVertexAttrib4fv;
	return true;
}

struct ChimeraGlEntry { const char *name; void *fn; };
static const struct ChimeraGlEntry g_entries[] = {
	{ "glActiveTexture", (void *)w_glActiveTexture },
	{ "glAttachShader", (void *)w_glAttachShader },
	{ "glBeginQuery", (void *)w_glBeginQuery },
	{ "glBindBuffer", (void *)w_glBindBuffer },
	{ "glBindFramebuffer", (void *)w_glBindFramebuffer },
	{ "glBindRenderbuffer", (void *)w_glBindRenderbuffer },
	{ "glBindTexture", (void *)w_glBindTexture },
	{ "glBindVertexArray", (void *)w_glBindVertexArray },
	{ "glBlendColor", (void *)w_glBlendColor },
	{ "glBlendFunc", (void *)w_glBlendFunc },
	{ "glBufferData", (void *)w_glBufferData },
	{ "glBufferSubData", (void *)w_glBufferSubData },
	{ "glCheckFramebufferStatus", (void *)w_glCheckFramebufferStatus },
	{ "glClear", (void *)w_glClear },
	{ "glClearColor", (void *)w_glClearColor },
	{ "glClearStencil", (void *)w_glClearStencil },
	{ "glClientWaitSync", (void *)w_glClientWaitSync },
	{ "glColorMask", (void *)w_glColorMask },
	{ "glCompileShader", (void *)w_glCompileShader },
	{ "glCreateProgram", (void *)w_glCreateProgram },
	{ "glCreateShader", (void *)w_glCreateShader },
	{ "glCullFace", (void *)w_glCullFace },
	{ "glDeleteBuffers", (void *)w_glDeleteBuffers },
	{ "glDeleteFramebuffers", (void *)w_glDeleteFramebuffers },
	{ "glDeleteProgram", (void *)w_glDeleteProgram },
	{ "glDeleteQueries", (void *)w_glDeleteQueries },
	{ "glDeleteRenderbuffers", (void *)w_glDeleteRenderbuffers },
	{ "glDeleteShader", (void *)w_glDeleteShader },
	{ "glDeleteSync", (void *)w_glDeleteSync },
	{ "glDeleteTextures", (void *)w_glDeleteTextures },
	{ "glDeleteVertexArrays", (void *)w_glDeleteVertexArrays },
	{ "glDepthFunc", (void *)w_glDepthFunc },
	{ "glDepthMask", (void *)w_glDepthMask },
	{ "glDisable", (void *)w_glDisable },
	{ "glDisableVertexAttribArray", (void *)w_glDisableVertexAttribArray },
	{ "glDrawArrays", (void *)w_glDrawArrays },
	{ "glDrawBuffers", (void *)w_glDrawBuffers },
	{ "glDrawElements", (void *)w_glDrawElements },
	{ "glEnable", (void *)w_glEnable },
	{ "glEnableVertexAttribArray", (void *)w_glEnableVertexAttribArray },
	{ "glEndQuery", (void *)w_glEndQuery },
	{ "glFenceSync", (void *)w_glFenceSync },
	{ "glFramebufferRenderbuffer", (void *)w_glFramebufferRenderbuffer },
	{ "glFramebufferTexture2D", (void *)w_glFramebufferTexture2D },
	{ "glGenBuffers", (void *)w_glGenBuffers },
	{ "glGenFramebuffers", (void *)w_glGenFramebuffers },
	{ "glGenQueries", (void *)w_glGenQueries },
	{ "glGenRenderbuffers", (void *)w_glGenRenderbuffers },
	{ "glGenTextures", (void *)w_glGenTextures },
	{ "glGenVertexArrays", (void *)w_glGenVertexArrays },
	{ "glGetError", (void *)w_glGetError },
	{ "glGetFloatv", (void *)w_glGetFloatv },
	{ "glGetIntegerv", (void *)w_glGetIntegerv },
	{ "glGetProgramBinary", (void *)w_glGetProgramBinary },
	{ "glGetProgramInfoLog", (void *)w_glGetProgramInfoLog },
	{ "glGetProgramiv", (void *)w_glGetProgramiv },
	{ "glGetShaderInfoLog", (void *)w_glGetShaderInfoLog },
	{ "glGetShaderiv", (void *)w_glGetShaderiv },
	{ "glGetString", (void *)w_glGetString },
	{ "glGetStringi", (void *)w_glGetStringi },
	{ "glGetUniformLocation", (void *)w_glGetUniformLocation },
	{ "glLineWidth", (void *)w_glLineWidth },
	{ "glLinkProgram", (void *)w_glLinkProgram },
	{ "glPixelStorei", (void *)w_glPixelStorei },
	{ "glPolygonMode", (void *)w_glPolygonMode },
	{ "glProgramBinary", (void *)w_glProgramBinary },
	{ "glReadBuffer", (void *)w_glReadBuffer },
	{ "glReadPixels", (void *)w_glReadPixels },
	{ "glRenderbufferStorage", (void *)w_glRenderbufferStorage },
	{ "glScissor", (void *)w_glScissor },
	{ "glShaderSource", (void *)w_glShaderSource },
	{ "glStencilFunc", (void *)w_glStencilFunc },
	{ "glStencilMask", (void *)w_glStencilMask },
	{ "glStencilOp", (void *)w_glStencilOp },
	{ "glTexImage2D", (void *)w_glTexImage2D },
	{ "glTexParameterf", (void *)w_glTexParameterf },
	{ "glTexParameterfv", (void *)w_glTexParameterfv },
	{ "glTexParameteri", (void *)w_glTexParameteri },
	{ "glUniform1f", (void *)w_glUniform1f },
	{ "glUniform1i", (void *)w_glUniform1i },
	{ "glUniform1ui", (void *)w_glUniform1ui },
	{ "glUniform2f", (void *)w_glUniform2f },
	{ "glUniform2fv", (void *)w_glUniform2fv },
	{ "glUniform2iv", (void *)w_glUniform2iv },
	{ "glUniform3f", (void *)w_glUniform3f },
	{ "glUniform3fv", (void *)w_glUniform3fv },
	{ "glUniform4f", (void *)w_glUniform4f },
	{ "glUniform4fv", (void *)w_glUniform4fv },
	{ "glUniform4iv", (void *)w_glUniform4iv },
	{ "glUniformMatrix2fv", (void *)w_glUniformMatrix2fv },
	{ "glUseProgram", (void *)w_glUseProgram },
	{ "glVertexAttribIPointer", (void *)w_glVertexAttribIPointer },
	{ "glVertexAttribPointer", (void *)w_glVertexAttribPointer },
	{ "glViewport", (void *)w_glViewport },
	{ "glBlendEquation", (void *)w_glBlendEquation },
	{ "glClearDepth", (void *)w_glClearDepth },
	{ "glDebugMessageInsert", (void *)w_glDebugMessageInsert },
	{ "glFinish", (void *)w_glFinish },
	{ "glFrameTerminatorGREMEDY", (void *)w_glFrameTerminatorGREMEDY },
	{ "glFrontFace", (void *)w_glFrontFace },
	{ "glGetQueryObjectuiv", (void *)w_glGetQueryObjectuiv },
	{ "glMultiDrawArrays", (void *)w_glMultiDrawArrays },
	{ "glObjectLabel", (void *)w_glObjectLabel },
	{ "glPopDebugGroup", (void *)w_glPopDebugGroup },
	{ "glProgramUniform1i", (void *)w_glProgramUniform1i },
	{ "glProgramUniform2f", (void *)w_glProgramUniform2f },
	{ "glProvokingVertex", (void *)w_glProvokingVertex },
	{ "glPushDebugGroup", (void *)w_glPushDebugGroup },
	{ "glTexImage3D", (void *)w_glTexImage3D },
	{ "glTexParameteriv", (void *)w_glTexParameteriv },
	{ "glUniform1fv", (void *)w_glUniform1fv },
	{ "glUniform1iv", (void *)w_glUniform1iv },
	{ "glUniform1uiv", (void *)w_glUniform1uiv },
	{ "glValidateProgram", (void *)w_glValidateProgram },
	{ "glVertexAttrib4fv", (void *)w_glVertexAttrib4fv },
};

/* What a glad loader asks for. Unknown names answer null, which is what glad
 * expects for an entry point the driver does not have. */
void *chimera_gl_lookup(const char *name)
{
	for (size_t i = 0; i < sizeof g_entries / sizeof *g_entries; i++)
	{
		if (std::strcmp(g_entries[i].name, name) == 0)
			return g_entries[i].fn;
	}

	return nullptr;
}
